In [1]:
import pandas as pd
import numpy as np

# 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/Wilcoxon_DEG_plasma_re.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(754, 5)
     names      scores  logfoldchanges  pvals  pvals_adj
0  MT-ND4L  143.157790        6.303974    0.0        0.0
1   MT-CO1  124.524230        3.418337    0.0        0.0
2  MT-ATP8  119.880790        6.173937    0.0        0.0
3   MT-CYB  112.181984        3.238582    0.0        0.0
4   MT-ND3  106.093370        3.423449    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        6.303974   0.0                0.0
1   MT-CO1        3.418337   0.0                0.0
2  MT-ATP8        6.173937   0.0                0.0
3   MT-CYB        3.238582   0.0                0.0
4   MT-ND3        3.423449   0.0                0.0

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        6.303974   0.0                0.0
1   MT-CO1        3.418337   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/limmatrend_DEG_plasma_re.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene", "pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(754, 6)
     names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0  MT-ND4L  4.940656e-324  4.940656e-324       -2.049300              NaN
1   MT-CO1  4.940656e-324  4.940656e-324       -2.339765              NaN

   neglog10_adjpvalue
0                 NaN
1                 NaN
     names  logfoldchanges          pvals      pvals_adj
0  MT-ND4L       -2.049300  4.940656e-324  4.940656e-324
1   MT-CO1       -2.339765  4.940656e-324  4.940656e-324
2  MT-ATP8       -1.188944  4.940656e-324  4.940656e-324
3   MT-CYB       -1.875336  4.940656e-324  4.940656e-324
4    RPL28       -1.433037  4.940656e-324  4.940656e-324
      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -2.049300  4.940656e-324        4.940656e-324
1   MT-CO1       -2.339765  4.940656e-324        4.940656e-324
2  MT-ATP8       -1.188944  4.940656e-324        4.940656e-324
3   MT-CYB       -1.875336  4.940656e-324        4.940656e-324
4    RPL28       -1.433037  4.940656e-324        4.940656e-324

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -2.049300  4.940656e-324        4.940656e-324
1   MT-CO1       -2.339765  4.940656e-324        4.940656e-324

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/RISCQP_DEG_plasma_re.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(754, 10)
  Unnamed: 0  Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      RPL22   RPL22    0.387    0.275    0.707    5.517591    2.060480
1      RPL11   RPL11    0.742    0.681    0.916    7.545238    5.634237
2      RSRP1   RSRP1    0.268    0.203    0.453    3.404060    1.561622
3       RPS8    RPS8    0.791    0.742    0.931    7.815298    6.239530
4     S100A6  S100A6    0.233    0.163    0.434    3.271543    1.256869

     log2FC  Pvalue  Padj
0 -5.178348     0.0   0.0
1 -2.761393     0.0   0.0
2 -2.949009     0.0   0.0
3 -2.275587     0.0   0.0
4 -3.333812     0.0   0.0
     gene    log2FC  pval  RISCQP_adj_pval
0   RPL22 -5.178348   0.0              0.0
1   RPL11 -2.761393   0.0              0.0
2   RSRP1 -2.949009   0.0              0.0
3    RPS8 -2.275587   0.0              0.0
4  S100A6 -3.333812   0.0              0.0

In [7]:
df_RISCQP.head(2)

    gene    log2FC  pval  RISCQP_adj_pval
0  RPL22 -5.178348   0.0              0.0
1  RPL11 -2.761393   0.0              0.0

In [8]:
# 4. monocle_deg 전처리
# DEG_monocle : monocle_DEG_-.csv

df_monocle = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_monocle/monocle_DEG_plasma.csv')
print(df_monocle.shape)
print(df_monocle.head())
df_monocle = df_monocle[["gene", "log2FC", "pvalue", "adjpvalue"]]
df_monocle.rename(columns={"pvalue": "pval","adjpvalue": "monocle_adj_pval"}, inplace=True)
print(df_monocle.head())

(754, 13)
   Unnamed: 0    gene  num_cells_expressed gene_id status      term    log2FC  \
0           1    BTG2                24319    BTG2     OK  GroupMSI  0.510769
1           2   RPL31                22625   RPL31     OK  GroupMSI -0.674929
2           3   RPL29                22727   RPL29     OK  GroupMSI  0.541422
3           4  NFKBIZ                 8909  NFKBIZ     OK  GroupMSI  1.055472
4           5    RPL9                29543    RPL9     OK  GroupMSI -0.639414

    std_err   test_val  pvalue  normalized_effect model_component  adjpvalue
0  0.012087  42.259008     0.0           0.729874           count        0.0
1  0.017187 -39.269071     0.0          -0.953705           count        0.0
2  0.012890  42.001933     0.0           0.770511           count        0.0
3  0.023921  44.122932     0.0           1.462571           count        0.0
4  0.013431 -47.607217     0.0          -0.912025           count        0.0
     gene    log2FC  pval  monocle_adj_pval
0    BTG2  0.510769   0.0               0.0
1   RPL31 -0.674929   0.0               0.0
2   RPL29  0.541422   0.0               0.0
3  NFKBIZ  1.055472   0.0               0.0
4    RPL9 -0.639414   0.0               0.0

In [9]:
df_monocle.head(2)

    gene    log2FC  pval  monocle_adj_pval
0   BTG2  0.510769   0.0               0.0
1  RPL31 -0.674929   0.0               0.0

In [10]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/MAST_DEG_plasma.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(754, 4)
    names  logfoldchanges          pvals      pvals_adj
0  ACADVL        0.012598  1.159201e-102  1.649128e-102
1    ACTB       -0.875591   0.000000e+00   0.000000e+00
     gene  logfoldchanges           pval  MAST_adj_pval
0  ACADVL        0.012598  1.159201e-102  1.649128e-102
1    ACTB       -0.875591   0.000000e+00   0.000000e+00
2   ACTG1       -0.127924   0.000000e+00   0.000000e+00
3    ADA2       -0.014230   1.028744e-29   1.098687e-29
4   AHNAK        0.034826  2.227263e-112  3.345332e-112

In [11]:
df_MAST.head(2)

     gene  logfoldchanges           pval  MAST_adj_pval
0  ACADVL        0.012598  1.159201e-102  1.649128e-102
1    ACTB       -0.875591   0.000000e+00   0.000000e+00

## <font color="red">**MSS/MSI 데이터프레임**

In [12]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    df_monocle[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(754, 6)
     gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0  ACADVL       7.049032e-03         5.214979e-02     7.316295e-13
1    ACTB       0.000000e+00        4.940656e-324     0.000000e+00
2   ACTG1       7.666829e-32         5.261055e-40    3.737873e-172
3    ADA2       2.281300e-04         3.622857e-03     1.059251e-07
4   AHNAK       5.482960e-08         5.858739e-04     4.183015e-07

   MAST_adj_pval  monocle_adj_pval
0  1.649128e-102      7.551340e-02
1   0.000000e+00      0.000000e+00
2   0.000000e+00      3.313070e-20
3   1.098687e-29      1.034902e-14
4  3.345332e-112      3.560422e-49

In [13]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval
0,ACADVL,0.007049,5.214979e-02,7.316295e-13,1.649128e-102,0.075513
1,ACTB,0.000000,4.940656e-324,0.000000e+00,0.000000e+00,0.000000

In [14]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_monocle'] = df_mmm['monocle_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']
].sum(axis=1)

# 3) sum_rank 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,rank_sum
0,ATF4,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
1,ATP5F1D,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
2,RPS26,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
3,SLC25A6,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
4,RPS10,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
749,H1-2,0.236768,9.041599e-03,0.360110,7.695870e-07,0.004760,729,711,733,749,582,3504
750,GALNT2,0.852996,2.707843e-07,0.818540,2.630151e-11,1.000000,752,659,749,741,642,3543
751,NRDC,0.308646,5.674914e-01,0.048753,1.291173e-06,0.407669,731,746,715,750,630,3572
752,NSD3,0.683710,6.029299e-01,0.264134,2.852270e-10,0.118346,743,748,728,744,620,3583
753,MIR23AHG,0.226704,5.833447e-01,0.418423,3.881634e-03,0.181389,728,747,734,753,624,3586

In [15]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']]
df_mmm_re.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle
0,5,ATF4,1,1,1,1,1
1,5,ATP5F1D,1,1,1,1,1
2,5,RPS26,1,1,1,1,1
3,5,SLC25A6,1,1,1,1,1
4,5,RPS10,1,1,1,1,1
5,5,RPL28,1,1,1,1,1
6,5,CD69,1,1,1,1,1
7,5,CD74,1,1,1,1,1
8,5,RPL27A,1,1,1,1,1
9,5,CYBA,1,1,1,1,1
10,5,RPL29,1,1,1,1,1
11,5,IGLL5,1,1,1,1,1
12,5,H4C3,1,1,1,1,1
13,5,ACTB,1,1,1,1,1
14,5,MT-ND4,1,1,1,1,1
15,5,MT-ND3,1,1,1,1,1
16,5,NFKBIZ,1,1,1,1,1
17,5,ENSG00000286264,1,1,1,1,1
18,5,MT-CYB,1,1,1,1,1
19,5,MT-CO3,1,1,1,1,1

In [16]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum             gene  rank_wilcoxon  rank_limma  rank_RISCQP  \
0          5             ATF4              1           1            1
1          5          ATP5F1D              1           1            1
18         5           MT-CYB              1           1            1
19         5           MT-CO3              1           1            1
6          5             CD69              1           1            1
7          5             CD74              1           1            1
9          5             CYBA              1           1            1
8          5           RPL27A              1           1            1
12         5             H4C3              1           1            1
13         5             ACTB              1           1            1
10         5            RPL29              1           1            1
11         5            IGLL5              1           1            1
14         5           MT-ND4              1           1            1
15         5           MT-ND3              1           1            1
17         5  ENSG00000286264              1           1            1
16         5           NFKBIZ              1           1            1
3          5          SLC25A6              1           1            1
34         5             FTH1              1           1            1
33         5             JUND              1           1            1
32         5             JUNB              1           1            1

    rank_MAST  rank_monocle Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign  \
0           1             1           MSS         MSS         MSS       MSS
1           1             1           MSI         MSI         MSI       MSI
18          1             1           MSI         MSI         MSI       MSI
19          1             1           MSI         MSI         MSI       MSI
6           1             1           MSI         MSI         MSI       MSI
7           1             1           MSI         MSI         MSI       MSI
9           1             1           MSI         MSI         MSI       MSI
8           1             1           MSS         MSS         MSS       MSS
12          1             1           MSI         MSI         MSI       MSI
13          1             1           MSI         MSI         MSI       MSI
10          1             1           MSI         MSI         MSI       MSI
11          1             1           MSS         MSS         MSS       MSS
14          1             1           MSI         MSI         MSI       MSI
15          1             1           MSI         MSI         MSI       MSI
17          1             1           MSS         MSS         MSS       MSS
16          1             1           MSI         MSI         MSI       MSI
3           1             1           MSI         MSI         MSI       MSI
34          1             1           MSI         MSI         MSI       MSI
33          1             1           MSS         MSS         MSS       MSS
32          1             1           MSI         MSI         MSI       MSI

   consensus
0   MSS_high
1   MSI_high
18  MSI_high
19  MSI_high
6   MSI_high
7   MSI_high
9   MSI_high
8   MSS_high
12  MSI_high
13  MSI_high
10  MSI_high
11  MSS_high
14  MSI_high
15  MSI_high
17  MSS_high
16  MSI_high
3   MSI_high
34  MSI_high
33  MSS_high
32  MSI_high

In [17]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
# df_final_filtered = (
#     df_final_filtered
#     .set_index('gene')
#     .loc[genes_of_interest]         # order 순서대로 행 재정렬
#     .reset_index()                  # 다시 gene을 컬럼으로
# )

df_final_filtered

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
721,3236,SDC1,744,686,709,613,484,MSS,MSS,MSI,MSS,MSS_high

In [18]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

/tmp/ipykernel_1189268/45665166.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_filtered['rank_mean'] = (

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
721,3236,SDC1,744,686,709,613,484,MSS,MSS,MSI,MSS,MSS_high,688