In [1]:
import pandas as pd
import numpy as np

# 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/Wilcoxon_DEG_myeloid_re.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(3215, 5)
     names     scores  logfoldchanges  pvals  pvals_adj
0    IFI30  164.91655        3.296234    0.0        0.0
1   RNASEK  158.14708        3.808206    0.0        0.0
2  GABARAP  151.23790        2.220161    0.0        0.0
3    EEF1G  132.91934        3.371008    0.0        0.0
4  ATP6V0C  131.40378        3.987060    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0    IFI30        3.296234   0.0                0.0
1   RNASEK        3.808206   0.0                0.0
2  GABARAP        2.220161   0.0                0.0
3    EEF1G        3.371008   0.0                0.0
4  ATP6V0C        3.987060   0.0                0.0

In [3]:
df_wilcoxon.head(2)

     gene  logfoldchanges  pval  Wilcoxon_adj_pval
0   IFI30        3.296234   0.0                0.0
1  RNASEK        3.808206   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend//limmatrend_DEG_myeloid_re.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(3215, 6)
    names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0   IFI30  4.940656e-324  4.940656e-324       -1.738705              NaN
1  RNASEK  4.940656e-324  4.940656e-324       -1.236138              NaN

   neglog10_adjpvalue
0                 NaN
1                 NaN
     names  logfoldchanges          pvals      pvals_adj
0    IFI30       -1.738705  4.940656e-324  4.940656e-324
1   RNASEK       -1.236138  4.940656e-324  4.940656e-324
2  GABARAP       -1.276008  4.940656e-324  4.940656e-324
3    RPS10        1.073592  4.940656e-324  4.940656e-324
4    EEF1G       -0.847613  4.940656e-324  4.940656e-324
      gene  logfoldchanges           pval  limmatrend_adj_pval
0    IFI30       -1.738705  4.940656e-324        4.940656e-324
1   RNASEK       -1.236138  4.940656e-324        4.940656e-324
2  GABARAP       -1.276008  4.940656e-324        4.940656e-324
3    RPS10        1.073592  4.940656e-324        4.940656e-324
4    EEF1G       -0.847613  4.940656e-324        4.940656e-324

In [5]:
df_limmatrend.head(2)

     gene  logfoldchanges           pval  limmatrend_adj_pval
0   IFI30       -1.738705  4.940656e-324        4.940656e-324
1  RNASEK       -1.236138  4.940656e-324        4.940656e-324

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/RISCQP_DEG_myeloid_re.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(3215, 10)
  Unnamed: 0  Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      ISG15   ISG15    0.412    0.524    0.285    1.863439    3.370898
1       GNB1    GNB1    0.473    0.602    0.327    2.088933    3.665265
2       RER1    RER1    0.408    0.527    0.273    1.722410    3.130729
3     CAMTA1  CAMTA1    0.346    0.454    0.225    1.414784    2.638505
4       RBP7    RBP7    0.332    0.252    0.421    2.802108    1.625852

     log2FC  Pvalue  Padj
0  2.367575     0.0   0.0
1  2.427456     0.0   0.0
2  2.251237     0.0   0.0
3  2.060072     0.0   0.0
4 -1.922732     0.0   0.0
     gene    log2FC  pval  RISCQP_adj_pval
0   ISG15  2.367575   0.0              0.0
1    GNB1  2.427456   0.0              0.0
2    RER1  2.251237   0.0              0.0
3  CAMTA1  2.060072   0.0              0.0
4    RBP7 -1.922732   0.0              0.0

In [7]:
df_RISCQP.head(2)

    gene    log2FC  pval  RISCQP_adj_pval
0  ISG15  2.367575   0.0              0.0
1   GNB1  2.427456   0.0              0.0

In [8]:
# 4. monocle_deg 전처리
# DEG_monocle : monocle_DEG_-.csv

df_monocle = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_monocle/monocle_DEG_myeloid.csv')
print(df_monocle.shape)
print(df_monocle.head())
df_monocle = df_monocle[["gene", "log2FC", "pvalue", "adjpvalue"]]
df_monocle.rename(columns={"pvalue": "pval","adjpvalue": "monocle_adj_pval"}, inplace=True)
print(df_monocle.head())

(3215, 13)
   Unnamed: 0   gene  num_cells_expressed          gene_id status      term  \
0           1    CDA                16085  ENSG00000158825     OK  GroupMSI
1           2   C1QA                14881  ENSG00000173372     OK  GroupMSI
2           3   C1QC                14230  ENSG00000159189     OK  GroupMSI
3           4   C1QB                14437  ENSG00000173369     OK  GroupMSI
4           5  CSF3R                30296  ENSG00000119535     OK  GroupMSI

     log2FC   std_err   test_val  pvalue  normalized_effect model_component  \
0  0.917914  0.024352  37.692802     0.0           1.247930           count
1 -3.271821  0.046122 -70.937874     0.0          -4.219584           count
2 -3.566515  0.056350 -63.292431     0.0          -4.436518           count
3 -3.513235  0.051802 -67.821028     0.0          -4.450499           count
4  0.759346  0.016279  46.646700     0.0           1.065910           count

   adjpvalue
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
    gene    log2FC  pval  monocle_adj_pval
0    CDA  0.917914   0.0               0.0
1   C1QA -3.271821   0.0               0.0
2   C1QC -3.566515   0.0               0.0
3   C1QB -3.513235   0.0               0.0
4  CSF3R  0.759346   0.0               0.0

In [9]:
df_monocle.head(2)

   gene    log2FC  pval  monocle_adj_pval
0   CDA  0.917914   0.0               0.0
1  C1QA -3.271821   0.0               0.0

In [10]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/MAST_DEG_myeloid.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(3215, 4)
  names  logfoldchanges  pvals  pvals_adj
0  A1BG       -0.034879    0.0        0.0
1   A2M        0.348949    0.0        0.0
   gene  logfoldchanges  pval  MAST_adj_pval
0  A1BG       -0.034879   0.0            0.0
1   A2M        0.348949   0.0            0.0
2  AAK1        0.045461   0.0            0.0
3  AAMP       -0.022229   0.0            0.0
4  AATF       -0.068205   0.0            0.0

In [11]:
df_MAST.head(2)

   gene  logfoldchanges  pval  MAST_adj_pval
0  A1BG       -0.034879   0.0            0.0
1   A2M        0.348949   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [12]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    df_monocle[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(3215, 6)
   gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0  A1BG       1.358291e-02         2.302797e-49     5.576901e-04
1   A2M       0.000000e+00        4.940656e-324     0.000000e+00
2  AAK1      1.434274e-224         4.370192e-65     0.000000e+00
3  AAMP       2.661649e-23         3.866463e-26     6.659791e-53
4  AATF       3.098426e-08        1.095485e-210     5.027097e-13

   MAST_adj_pval  monocle_adj_pval
0            0.0      3.770000e-09
1            0.0      0.000000e+00
2            0.0      6.330000e-36
3            0.0      6.750000e-05
4            0.0      4.760000e-54

In [13]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval
0,A1BG,0.013583,2.302797e-49,0.000558,0.0,3.770000e-09
1,A2M,0.000000,4.940656e-324,0.000000,0.0,0.000000e+00

In [14]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_monocle'] = df_mmm['monocle_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']
].sum(axis=1)

# 3) sum_rank 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,rank_sum
0,TKT,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
1,ATP6V0C,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
2,POLD4,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
3,PLTP,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
4,PMP22,0.000000,4.940656e-324,0.000000,0.000000e+00,0.000000,1,1,1,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
3210,MCEMP1,0.249617,4.228019e-02,0.637421,2.060389e-03,0.006593,3119,3023,3185,3215,2405,14947
3211,RPL36,0.331469,1.368982e-03,0.147703,1.273069e-16,1.000000,3135,2904,3120,3203,2623,14985
3212,ITM2B,0.358486,7.241696e-03,0.017321,1.304431e-03,1.000000,3143,2961,3072,3214,2623,15013
3213,CYBA,0.778317,2.355752e-03,0.721389,4.450964e-07,1.000000,3191,2920,3193,3211,2623,15138
3214,HLA-A,0.673115,9.199101e-01,0.004930,4.464282e-04,1.000000,3179,3203,3046,3213,2623,15264

In [15]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']]
df_mmm_re.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle
0,5,TKT,1,1,1,1,1
1,5,ATP6V0C,1,1,1,1,1
2,5,POLD4,1,1,1,1,1
3,5,PLTP,1,1,1,1,1
4,5,PMP22,1,1,1,1,1
5,5,BASP1,1,1,1,1,1
6,5,IL1B,1,1,1,1,1
7,5,POU2F2,1,1,1,1,1
8,5,RPS26,1,1,1,1,1
9,5,RPS29,1,1,1,1,1
10,5,CORO1A,1,1,1,1,1
11,5,EIF4A1,1,1,1,1,1
12,5,S100A12,1,1,1,1,1
13,5,GPR34,1,1,1,1,1
14,5,ITGA4,1,1,1,1,1
15,5,TLN1,1,1,1,1,1
16,5,CD163,1,1,1,1,1
17,5,GLUL,1,1,1,1,1
18,5,IGKC,1,1,1,1,1
19,5,IL17RA,1,1,1,1,1

In [16]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# monocle: log2FC >0 → MSI, <0 → MSS
sign_dfs.append(
    df_monocle[['gene','log2FC']]
    .assign(monocle_sign=lambda d: d['log2FC'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','monocle_sign']]
)

# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
64         5  HERPUD1              1           1            1          1
65         5   STXBP2              1           1            1          1
66         5    FABP5              1           1            1          1
67         5     H1-4              1           1            1          1
68         5     MRC1              1           1            1          1
69         5    RPS20              1           1            1          1
70         5     NCF1              1           1            1          1
71         5  SLC40A1              1           1            1          1
72         5    ACAP2              1           1            1          1
73         5    CXCL2              1           1            1          1
74         5    CXCL3              1           1            1          1
75         5    CXCL8              1           1            1          1
76         5    CXCR4              1           1            1          1
77         5   MS4A4A              1           1            1          1
94         5   RPL27A              1           1            1          1
95         5    TOMM6              1           1            1          1
96         5  TNFAIP3              1           1            1          1
97         5   SAMSN1              1           1            1          1
98         5   HSPA1B              1           1            1          1
99         5  TNFSF10              1           1            1          1

    rank_monocle Wilcoxon_sign limmat_sign RISCQP_sign monocle_sign MAST_sign  \
64             1           MSS         MSS         MSS          MSS       MSS
65             1           MSI         MSI         MSI          MSI       MSI
66             1           MSS         MSS         MSS          MSS       MSS
67             1           MSI         MSI         MSI          MSI       MSI
68             1           MSS         MSS         MSS          MSS       MSS
69             1           MSS         MSS         MSS          MSS       MSS
70             1           MSI         MSI         MSI          MSI       MSI
71             1           MSS         MSS         MSS          MSS       MSS
72             1           MSI         MSI         MSI          MSI       MSI
73             1           MSS         MSS         MSS          MSS       MSS
74             1           MSS         MSS         MSS          MSS       MSS
75             1           MSS         MSS         MSS          MSS       MSS
76             1           MSS         MSS         MSS          MSS       MSS
77             1           MSS         MSS         MSS          MSS       MSS
94             1           MSS         MSS         MSS          MSS       MSS
95             1           MSI         MSI         MSI          MSI       MSI
96             1           MSS         MSS         MSS          MSS       MSS
97             1           MSS         MSS         MSS          MSS       MSS
98             1           MSS         MSS         MSS          MSS       MSS
99             1           MSI         MSI         MSI          MSI       MSI

   consensus
64  MSS_high
65  MSI_high
66  MSS_high
67  MSI_high
68  MSS_high
69  MSS_high
70  MSI_high
71  MSS_high
72  MSI_high
73  MSS_high
74  MSS_high
75  MSS_high
76  MSS_high
77  MSS_high
94  MSS_high
95  MSI_high
96  MSS_high
97  MSS_high
98  MSS_high
99  MSI_high

In [17]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,Wilcoxon_sign,limmat_sign,RISCQP_sign,monocle_sign,MAST_sign,consensus
0,5,TKT,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
1,5,ATP6V0C,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
2,5,POLD4,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
3,5,PLTP,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
4,5,PMP22,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
5,5,BASP1,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
6,5,IL1B,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
7,5,POU2F2,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
8,5,RPS26,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
9,5,RPS29,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
10,5,CORO1A,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
11,5,EIF4A1,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
12,5,S100A12,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
13,5,GPR34,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
14,5,ITGA4,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
15,5,TLN1,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high
16,5,CD163,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
17,5,GLUL,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
18,5,IGKC,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high
19,5,IL17RA,1,1,1,1,1,MSI,MSI,MSI,MSI,MSI,MSI_high

In [18]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
# df_final_filtered = (
#     df_final_filtered
#     .set_index('gene')
#     .loc[genes_of_interest]         # order 순서대로 행 재정렬
#     .reset_index()                  # 다시 gene을 컬럼으로
# )

df_final_filtered

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,Wilcoxon_sign,limmat_sign,RISCQP_sign,monocle_sign,MAST_sign,consensus
121,5,VSIG4,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high

In [19]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

/tmp/ipykernel_1187224/45665166.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final_filtered['rank_mean'] = (

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,Wilcoxon_sign,limmat_sign,RISCQP_sign,monocle_sign,MAST_sign,consensus,rank_mean
121,5,VSIG4,1,1,1,1,1,MSS,MSS,MSS,MSS,MSS,MSS_high,1