In [2]:
import pandas as pd
import numpy as np

# 데이터 정제

In [3]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/Wilcoxon_DEG_bcell_re.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(1295, 5)
     names      scores  logfoldchanges  pvals  pvals_adj
0  PTPRCAP  135.248150        5.784529    0.0        0.0
1  MT-ATP8  123.874405        3.806541    0.0        0.0
2     CD74  123.015730        0.566575    0.0        0.0
3  MT-ND4L  110.497930        2.406979    0.0        0.0
4    EEF1G   96.309060        3.170278    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  PTPRCAP        5.784529   0.0                0.0
1  MT-ATP8        3.806541   0.0                0.0
2     CD74        0.566575   0.0                0.0
3  MT-ND4L        2.406979   0.0                0.0
4    EEF1G        3.170278   0.0                0.0

In [4]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  PTPRCAP        5.784529   0.0                0.0
1  MT-ATP8        3.806541   0.0                0.0

In [5]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/limmatrend_DEG_B_cell_re.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene", "pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(1295, 6)
   names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0  RPS10  4.940656e-324  4.940656e-324        1.714055              NaN
1   CD74  4.940656e-324  4.940656e-324       -1.498023              NaN

   neglog10_adjpvalue
0                 NaN
1                 NaN
     names  logfoldchanges          pvals      pvals_adj
0    RPS10        1.714055  4.940656e-324  4.940656e-324
1     CD74       -1.498023  4.940656e-324  4.940656e-324
2  PTPRCAP       -1.267538  4.940656e-324  4.940656e-324
3     JUND        1.827575  4.940656e-324  4.940656e-324
4  MT-ATP8       -1.212474  4.940656e-324  4.940656e-324
      gene  logfoldchanges           pval  limmatrend_adj_pval
0    RPS10        1.714055  4.940656e-324        4.940656e-324
1     CD74       -1.498023  4.940656e-324        4.940656e-324
2  PTPRCAP       -1.267538  4.940656e-324        4.940656e-324
3     JUND        1.827575  4.940656e-324        4.940656e-324
4  MT-ATP8       -1.212474  4.940656e-324        4.940656e-324

In [6]:
df_limmatrend.head(2)

    gene  logfoldchanges           pval  limmatrend_adj_pval
0  RPS10        1.714055  4.940656e-324        4.940656e-324
1   CD74       -1.498023  4.940656e-324        4.940656e-324

In [7]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/RISCQP_DEG_B_cell_re.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(1295, 10)
  Unnamed: 0    Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      RPL22     RPL22    0.894    0.817    0.982    7.777200    6.436349
1   SH3BGRL3  SH3BGRL3    0.692    0.573    0.830    6.204494    4.187657
2        JUN       JUN    0.651    0.753    0.532    3.951688    5.840002
3     ATP5PB    ATP5PB    0.294    0.204    0.399    2.803687    1.412644
4   C1orf162  C1orf162    0.203    0.108    0.312    2.197912    0.758130

     log2FC  Pvalue  Padj
0 -1.936147     0.0   0.0
1 -2.928834     0.0   0.0
2  2.748059     0.0   0.0
3 -2.319268     0.0   0.0
4 -2.819337     0.0   0.0
       gene    log2FC  pval  RISCQP_adj_pval
0     RPL22 -1.936147   0.0              0.0
1  SH3BGRL3 -2.928834   0.0              0.0
2       JUN  2.748059   0.0              0.0
3    ATP5PB -2.319268   0.0              0.0
4  C1orf162 -2.819337   0.0              0.0

In [8]:
df_RISCQP.head(2)

       gene    log2FC  pval  RISCQP_adj_pval
0     RPL22 -1.936147   0.0              0.0
1  SH3BGRL3 -2.928834   0.0              0.0

In [9]:
# 4. monocle_deg 전처리
# DEG_monocle : monocle_DEG_-.csv

df_monocle = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_monocle/monocle_DEG_bcell.csv')
print(df_monocle.shape)
print(df_monocle.head())
df_monocle = df_monocle[["gene", "log2FC", "pvalue", "adjpvalue"]]
df_monocle.rename(columns={"pvalue": "pval","adjpvalue": "monocle_adj_pval"}, inplace=True)
print(df_monocle.head())

(1295, 13)
   Unnamed: 0   gene  num_cells_expressed gene_id status      term    log2FC  \
0           1  RCSD1                16543   RCSD1     OK  GroupMSI  0.712003
1           2   SELL                13812    SELL     OK  GroupMSI  0.710306
2           3   IER5                 7552    IER5     OK  GroupMSI -1.469146
3           4   RGS1                 9823    RGS1     OK  GroupMSI -1.331782
4           5   RGS2                11387    RGS2     OK  GroupMSI -0.928969

    std_err   test_val  pvalue  normalized_effect model_component  adjpvalue
0  0.016333  43.593679     0.0           1.006945           count        0.0
1  0.017602  40.354350     0.0           1.001015           count        0.0
2  0.035227 -41.705548     0.0          -1.982816           count        0.0
3  0.027099 -49.145728     0.0          -1.848833           count        0.0
4  0.022027 -42.174568     0.0          -1.298845           count        0.0
    gene    log2FC  pval  monocle_adj_pval
0  RCSD1  0.712003   0.0               0.0
1   SELL  0.710306   0.0               0.0
2   IER5 -1.469146   0.0               0.0
3   RGS1 -1.331782   0.0               0.0
4   RGS2 -0.928969   0.0               0.0

In [10]:
df_monocle.head(2)

    gene    log2FC  pval  monocle_adj_pval
0  RCSD1  0.712003   0.0               0.0
1   SELL  0.710306   0.0               0.0

In [11]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/MAST_DEG_B_Cell.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(1295, 4)
   names  logfoldchanges          pvals      pvals_adj
0  ACAP1        0.048059   5.429220e-27   6.975040e-27
1  ACAP2       -0.156392  1.677736e-285  6.685134e-285
    gene  logfoldchanges           pval  MAST_adj_pval
0  ACAP1        0.048059   5.429220e-27   6.975040e-27
1  ACAP2       -0.156392  1.677736e-285  6.685134e-285
2   ACP1       -0.079046  6.532622e-101  1.291564e-100
3   ACTB       -1.058832   0.000000e+00   0.000000e+00
4  ACTG1       -0.209270  9.132573e-196  2.706335e-195

In [12]:
df_MAST.head(2)

    gene  logfoldchanges           pval  MAST_adj_pval
0  ACAP1        0.048059   5.429220e-27   6.975040e-27
1  ACAP2       -0.156392  1.677736e-285  6.685134e-285

## <font color="red">**MSS/MSI 데이터프레임**

In [13]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    df_monocle[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(1295, 6)
    gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0  ACAP1       1.490055e-09         1.173677e-22     1.153525e-12
1  ACAP2      1.691411e-192        3.235876e-244    5.226208e-267
2   ACP1       8.407062e-47         1.427846e-99     2.910424e-78
3   ACTB       0.000000e+00        4.940656e-324     0.000000e+00
4  ACTG1       1.198289e-69        9.584355e-129    1.908899e-173

   MAST_adj_pval  monocle_adj_pval
0   6.975040e-27      9.578917e-13
1  6.685134e-285      1.647643e-89
2  1.291564e-100      3.624737e-16
3   0.000000e+00      0.000000e+00
4  2.706335e-195      6.707738e-09

In [14]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval
0,ACAP1,1.490055e-09,1.173677e-22,1.153525e-12,6.975040e-27,9.578917e-13
1,ACAP2,1.691411e-192,3.235876e-244,5.226208e-267,6.685134e-285,1.647643e-89

In [15]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_monocle'] = df_mmm['monocle_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']
].sum(axis=1)

# 3) sum_rank 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,monocle_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle,rank_sum
0,ACTB,0.000000,4.940656e-324,0.000000,0.000000,0.000000,1,1,1,1,1,5
1,TCL1A,0.000000,4.940656e-324,0.000000,0.000000,0.000000,1,1,1,1,1,5
2,TAMALIN,0.000000,4.940656e-324,0.000000,0.000000,0.000000,1,1,1,1,1,5
3,GABARAP,0.000000,4.940656e-324,0.000000,0.000000,0.000000,1,1,1,1,1,5
4,SRGN,0.000000,4.940656e-324,0.000000,0.000000,0.000000,1,1,1,1,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1290,TPM4,0.356109,4.049669e-01,0.989383,0.155938,1.000000,1255,1260,1294,1284,1109,6202
1291,TAPBP,0.908877,2.989850e-01,0.908921,0.004763,1.000000,1293,1249,1288,1265,1109,6204
1292,UBE2N,0.383623,4.330287e-01,0.993450,0.101060,1.000000,1259,1264,1295,1281,1109,6208
1293,IRF1,0.991194,8.801024e-01,0.842330,0.651078,0.700132,1295,1289,1287,1293,1099,6263
1294,UFM1,0.781029,8.852288e-01,0.973058,0.788782,1.000000,1280,1290,1293,1295,1109,6267

In [16]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST', 'rank_monocle']]
df_mmm_re.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_monocle
0,5,ACTB,1,1,1,1,1
1,5,TCL1A,1,1,1,1,1
2,5,TAMALIN,1,1,1,1,1
3,5,GABARAP,1,1,1,1,1
4,5,SRGN,1,1,1,1,1
5,5,FOSB,1,1,1,1,1
6,5,FXYD5,1,1,1,1,1
7,5,GNAS,1,1,1,1,1
8,5,FOS,1,1,1,1,1
9,5,ATP1B3,1,1,1,1,1
10,5,HLA-DRB5,1,1,1,1,1
11,5,H1-4,1,1,1,1,1
12,5,GPR183,1,1,1,1,1
13,5,SAT1,1,1,1,1,1
14,5,SELL,1,1,1,1,1
15,5,ATP6V0C,1,1,1,1,1
16,5,RPL17,1,1,1,1,1
17,5,RPL23,1,1,1,1,1
18,5,RBM38,1,1,1,1,1
19,5,RNASEK,1,1,1,1,1

In [17]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_mmm_re_filtered = df_mmm_re[df_mmm_re["gene"].isin(genes_of_interest)]
df_mmm_re_filtered

Empty DataFrame
Columns: [rank_sum, gene, rank_wilcoxon, rank_limma, rank_RISCQP, rank_MAST, rank_monocle]
Index: []