In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [1]:
import pandas as pd
import numpy as np

### 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Mast_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names     scores  logfoldchanges          pvals      pvals_adj
0  MT-ND4L  29.577090        2.949751  2.945506e-192  4.193811e-188
1     ACTB  28.513615        1.353704  7.942646e-179  7.539159e-175
2    HSPA8  26.594760        2.017142  7.804425e-156  4.444776e-152
3    RPS26  26.573017        2.572682  1.392319e-155  6.607944e-152
4   NFKBIZ  25.266998        1.964584  7.367272e-141  2.997006e-137
      gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  MT-ND4L        2.949751  2.945506e-192      4.193811e-188
1     ACTB        1.353704  7.942646e-179      7.539159e-175
2    HSPA8        2.017142  7.804425e-156      4.444776e-152
3    RPS26        2.572682  1.392319e-155      6.607944e-152
4   NFKBIZ        1.964584  7.367272e-141      2.997006e-137

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  MT-ND4L        2.949751  2.945506e-192      4.193811e-188
1     ACTB        1.353704  7.942646e-179      7.539159e-175

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_mast_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 4)
     names          pvals      pvals_adj  logfoldchanges
0  MT-ND4L  5.740958e-105  1.634795e-100       -1.237962
1     JUND  7.296799e-102   1.038918e-97        1.409539
     names  logfoldchanges          pvals      pvals_adj
0  MT-ND4L       -1.237962  5.740958e-105  1.634795e-100
1     JUND        1.409539  7.296799e-102   1.038918e-97
2    RPS10        0.994670   7.715842e-82   7.323878e-78
3    HSPA8       -1.224826   9.910354e-79   7.055181e-75
4    RPS26       -1.083726   2.448182e-78   1.394289e-74
      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -1.237962  5.740958e-105        1.634795e-100
1     JUND        1.409539  7.296799e-102         1.038918e-97
2    RPS10        0.994670   7.715842e-82         7.323878e-78
3    HSPA8       -1.224826   9.910354e-79         7.055181e-75
4    RPS26       -1.083726   2.448182e-78         1.394289e-74

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-ND4L       -1.237962  5.740958e-105        1.634795e-100
1     JUND        1.409539  7.296799e-102         1.038918e-97

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_mast_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(14380, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0    MT-ND4L  MT-ND4L    0.576    0.380    0.946    6.913337    2.689454
1       JUND     JUND    0.679    0.836    0.380    2.563156    6.277897
2      RPS26    RPS26    0.581    0.410    0.904    6.589367    2.897382
3    MT-ATP8  MT-ATP8    0.326    0.147    0.664    4.573509    1.001987
4      RPS10    RPS10    0.447    0.649    0.066    0.432864    4.739874

     log2FC         Pvalue           Padj
0 -6.193811  3.574029e-176  5.139453e-172
1  5.472220  3.732820e-155  2.683898e-151
2 -5.406293  4.967095e-142  2.380894e-138
3 -5.797710  1.269448e-140  4.563664e-137
4  7.710050  1.005224e-131  2.891024e-128
      gene    log2FC           pval  RISCQP_adj_pval
0  MT-ND4L -6.193811  3.574029e-176    5.139453e-172
1     JUND  5.472220  3.732820e-155    2.683898e-151
2    RPS26 -5.406293  4.967095e-142    2.380894e-138
3  MT-ATP8 -5.797710  1.269448e-140    4.563664e-137
4    RPS10  7.710050  1.005224e-131    2.891024e-128

In [7]:
df_RISCQP.head(2)

      gene    log2FC           pval  RISCQP_adj_pval
0  MT-ND4L -6.193811  3.574029e-176    5.139453e-172
1     JUND  5.472220  3.732820e-155    2.683898e-151

In [8]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_mast_cell.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
     names  logfoldchanges          pvals      pvals_adj
0    RPS29        0.985891  1.179335e-320  3.358273e-316
1  MT-ND4L       -1.236665  1.731383e-296  2.465144e-292
      gene  logfoldchanges           pval  MAST_adj_pval
0    RPS29        0.985891  1.179335e-320  3.358273e-316
1  MT-ND4L       -1.236665  1.731383e-296  2.465144e-292
2    RPL41        0.606631  5.751650e-294  5.459466e-290
3     JUND        1.408842  9.015915e-294  6.418430e-290
4   MT-ND3        0.476219  5.980532e-274  3.406033e-270

In [9]:
df_MAST.head(2)

      gene  logfoldchanges           pval  MAST_adj_pval
0    RPS29        0.985891  1.179335e-320  3.358273e-316
1  MT-ND4L       -1.236665  1.731383e-296  2.465144e-292

## <font color="red">**MSS/MSI 데이터프레임**

In [10]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [11]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [12]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,MT-ND4L,4.193811e-188,1.634795e-100,5.139453e-172,2.465144e-292,2,1,1,2,6
1,JUND,1.830730e-220,1.038918e-97,2.683898e-151,6.418430e-290,1,2,2,4,9
2,RPS10,1.105945e-171,7.323878e-78,2.891024e-128,1.647665e-268,4,3,5,7,19
3,RPS26,6.607944e-152,1.394289e-74,2.380894e-138,1.308789e-210,6,5,3,16,30
4,HSPA8,4.444776e-152,7.055181e-75,3.386800e-98,1.300917e-213,5,4,13,15,37
...,...,...,...,...,...,...,...,...,...,...
28471,5_8S_rRNA-1,1.000000e+00,1.000000e+00,NaN,1.000000e+00,2338,14712,14381,15801,47232
28472,5_8S_rRNA,1.000000e+00,1.000000e+00,NaN,1.000000e+00,2338,14712,14381,15801,47232
28473,5S_rRNA-5,1.000000e+00,1.000000e+00,NaN,1.000000e+00,2338,14712,14381,15801,47232
28474,hsa-mir-8069-1,1.000000e+00,1.000000e+00,NaN,1.000000e+00,2338,14712,14381,15801,47232
28475,5S_rRNA-2,1.000000e+00,1.000000e+00,NaN,1.000000e+00,2338,14712,14381,15801,47232

In [13]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']].rename(columns={'sum_rank':'rank_sum'})
df_mmm_re.head(20)

    rank_sum      gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0          6   MT-ND4L              2           1            1          2
1          9      JUND              1           2            2          4
2         19     RPS10              4           3            5          7
3         30     RPS26              6           5            3         16
4         37     HSPA8              5           4           13         15
5         40     RPLP0             10           9            8         13
6         54   MT-ATP8             12          11            4         27
7         56      ACTB              3          10           34          9
8         66    NFKBIZ              7          12           14         33
9         67     TPSD1              8           7            6         46
10        79     RPL10             30           8           27         14
11        82     RPL29             33          13           10         26
12        88      CD81             16          21           17         34
13        95     RPL28             46          14            7         28
14       100    RPS4Y1             22          18            9         51
15       117   ATP6V0C             21          31           11         54
16       123  PPP1R15A             15          19           48         41
17       129    MAP3K8             24          23           21         61
18       132    RPL27A             11          20           82         19
19       135     ANXA1             17          16           71         31

In [14]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum      gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
0          6   MT-ND4L              2           1            1          2
1          9      JUND              1           2            2          4
2         19     RPS10              4           3            5          7
3         30     RPS26              6           5            3         16
4         37     HSPA8              5           4           13         15
5         40     RPLP0             10           9            8         13
6         54   MT-ATP8             12          11            4         27
7         56      ACTB              3          10           34          9
8         66    NFKBIZ              7          12           14         33
9         67     TPSD1              8           7            6         46
10        79     RPL10             30           8           27         14
11        82     RPL29             33          13           10         26
12        88      CD81             16          21           17         34
13        95     RPL28             46          14            7         28
14       100    RPS4Y1             22          18            9         51
15       117   ATP6V0C             21          31           11         54
16       123  PPP1R15A             15          19           48         41
17       129    MAP3K8             24          23           21         61
18       132    RPL27A             11          20           82         19
19       135     ANXA1             17          16           71         31

   Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
0            MSI         MSI         MSI       MSI  MSI_high
1            MSS         MSS         MSS       MSS  MSS_high
2            MSS         MSS         MSS       MSS  MSS_high
3            MSI         MSI         MSI       MSI  MSI_high
4            MSI         MSI         MSI       MSI  MSI_high
5            MSI         MSI         MSI       MSI  MSI_high
6            MSI         MSI         MSI       MSI  MSI_high
7            MSI         MSI         MSI       MSI  MSI_high
8            MSI         MSI         MSI       MSI  MSI_high
9            MSI         MSI         MSI       MSI  MSI_high
10           MSI         MSI         MSI       MSI  MSI_high
11           MSI         MSI         MSI       MSI  MSI_high
12           MSS         MSS         MSS       MSS  MSS_high
13           MSI         MSI         MSI       MSI  MSI_high
14           MSI         MSI         MSI       MSI  MSI_high
15           MSI         MSI         MSI       MSI  MSI_high
16           MSI         MSI         MSI       MSI  MSI_high
17           MSI         MSI         MSI       MSI  MSI_high
18           MSS         MSS         MSS       MSS  MSS_high
19           MSI         MSI         MSI       MSI  MSI_high

In [15]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,6,MT-ND4L,2,1,1,2,MSI,MSI,MSI,MSI,MSI_high
1,9,JUND,1,2,2,4,MSS,MSS,MSS,MSS,MSS_high
2,19,RPS10,4,3,5,7,MSS,MSS,MSS,MSS,MSS_high
3,30,RPS26,6,5,3,16,MSI,MSI,MSI,MSI,MSI_high
4,37,HSPA8,5,4,13,15,MSI,MSI,MSI,MSI,MSI_high
5,40,RPLP0,10,9,8,13,MSI,MSI,MSI,MSI,MSI_high
6,54,MT-ATP8,12,11,4,27,MSI,MSI,MSI,MSI,MSI_high
7,56,ACTB,3,10,34,9,MSI,MSI,MSI,MSI,MSI_high
8,66,NFKBIZ,7,12,14,33,MSI,MSI,MSI,MSI,MSI_high
9,67,TPSD1,8,7,6,46,MSI,MSI,MSI,MSI,MSI_high
10,79,RPL10,30,8,27,14,MSI,MSI,MSI,MSI,MSI_high
11,82,RPL29,33,13,10,26,MSI,MSI,MSI,MSI,MSI_high
12,88,CD81,16,21,17,34,MSS,MSS,MSS,MSS,MSS_high
13,95,RPL28,46,14,7,28,MSI,MSI,MSI,MSI,MSI_high
14,100,RPS4Y1,22,18,9,51,MSI,MSI,MSI,MSI,MSI_high
15,117,ATP6V0C,21,31,11,54,MSI,MSI,MSI,MSI,MSI_high
16,123,PPP1R15A,15,19,48,41,MSI,MSI,MSI,MSI,MSI_high
17,129,MAP3K8,24,23,21,61,MSI,MSI,MSI,MSI,MSI_high
18,132,RPL27A,11,20,82,19,MSS,MSS,MSS,MSS,MSS_high
19,135,ANXA1,17,16,71,31,MSI,MSI,MSI,MSI,MSI_high

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,28925,2338,6442,12785,7360,MSS,MSS,MSI,MSS,MSS_high
1,LYVE1,33738,2338,6951,14381,10068,MSI,MSI,NaN,MSS,MSS_high
2,CLEC5A,41040,2338,11351,14381,12970,MSS,MSS,NaN,MSS,MSS_high
3,CX3CR1,47232,2338,14712,14381,15801,MSS,MSS,NaN,MSS,MSS_high
4,FN1,19388,2338,4134,5690,7226,MSS,MSS,MSS,MSS,MSS_high
5,IL11,39050,2338,11351,9560,15801,MSI,MSI,MSI,MSI,MSI_high
6,NRAP,47232,2338,14712,14381,15801,MSS,MSS,NaN,MSS,MSS_high
7,SDC1,40857,2338,11351,11367,15801,MSS,MSS,MSS,MSS,MSS_high
8,SCG5,31475,2338,9708,7427,12002,MSS,MSS,MSS,MSS,MSS_high

In [17]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,28925,2338,6442,12785,7360,MSS,MSS,MSI,MSS,MSS_high,7231
1,LYVE1,33738,2338,6951,14381,10068,MSI,MSI,NaN,MSS,MSS_high,8434
2,CLEC5A,41040,2338,11351,14381,12970,MSS,MSS,NaN,MSS,MSS_high,10260
3,CX3CR1,47232,2338,14712,14381,15801,MSS,MSS,NaN,MSS,MSS_high,11808
4,FN1,19388,2338,4134,5690,7226,MSS,MSS,MSS,MSS,MSS_high,4847
5,IL11,39050,2338,11351,9560,15801,MSI,MSI,MSI,MSI,MSI_high,9762
6,NRAP,47232,2338,14712,14381,15801,MSS,MSS,NaN,MSS,MSS_high,11808
7,SDC1,40857,2338,11351,11367,15801,MSS,MSS,MSS,MSS,MSS_high,10214
8,SCG5,31475,2338,9708,7427,12002,MSS,MSS,MSS,MSS,MSS_high,7869