In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [1]:
import pandas as pd
import numpy as np

### 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Plasma_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names      scores  logfoldchanges  pvals  pvals_adj
0  MT-ND4L  143.157790        6.303974    0.0        0.0
1   MT-CO1  124.524230        3.418337    0.0        0.0
2  MT-ATP8  119.880790        6.173937    0.0        0.0
3   MT-CYB  112.181984        3.238582    0.0        0.0
4   MT-ND3  106.093370        3.423449    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        6.303974   0.0                0.0
1   MT-CO1        3.418337   0.0                0.0
2  MT-ATP8        6.173937   0.0                0.0
3   MT-CYB        3.238582   0.0                0.0
4   MT-ND3        3.423449   0.0                0.0

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        6.303974   0.0                0.0
1   MT-CO1        3.418337   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_plasma_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 4)
     names  pvals  pvals_adj  logfoldchanges
0  MT-ND4L    0.0        0.0       -1.572465
1  MT-ATP8    0.0        0.0       -1.221551
     names  logfoldchanges  pvals  pvals_adj
0  MT-ND4L       -1.572465    0.0        0.0
1  MT-ATP8       -1.221551    0.0        0.0
2  MT-RNR2        2.366534    0.0        0.0
3    RPL28       -1.206565    0.0        0.0
4   MT-CO1       -1.771133    0.0        0.0
      gene  logfoldchanges  pval  limmatrend_adj_pval
0  MT-ND4L       -1.572465   0.0                  0.0
1  MT-ATP8       -1.221551   0.0                  0.0
2  MT-RNR2        2.366534   0.0                  0.0
3    RPL28       -1.206565   0.0                  0.0
4   MT-CO1       -1.771133   0.0                  0.0

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges  pval  limmatrend_adj_pval
0  MT-ND4L       -1.572465   0.0                  0.0
1  MT-ATP8       -1.221551   0.0                  0.0

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_b_cell_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(20128, 10)
  Unnamed: 0    Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      RPL22     RPL22    0.894    0.817    0.982    7.312864    6.063652
1      RUNX3     RUNX3    0.171    0.257    0.072    0.462783    1.699150
2   SH3BGRL3  SH3BGRL3    0.692    0.573    0.830    5.810756    3.919092
3        JUN       JUN    0.651    0.753    0.532    3.699936    5.481283
4     ATP5PB    ATP5PB    0.294    0.204    0.399    2.613024    1.308258

     log2FC  Pvalue  Padj
0 -1.804630     0.0   0.0
1  2.924962     0.0   0.0
2 -2.753706     0.0   0.0
3  2.600040     0.0   0.0
4 -2.227141     0.0   0.0
       gene    log2FC  pval  RISCQP_adj_pval
0     RPL22 -1.804630   0.0              0.0
1     RUNX3  2.924962   0.0              0.0
2  SH3BGRL3 -2.753706   0.0              0.0
3       JUN  2.600040   0.0              0.0
4    ATP5PB -2.227141   0.0              0.0

In [7]:
df_RISCQP.head(2)

    gene    log2FC  pval  RISCQP_adj_pval
0  RPL22 -1.804630   0.0              0.0
1  RUNX3  2.924962   0.0              0.0

In [8]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_plasma.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
     names  logfoldchanges  pvals  pvals_adj
0     A1BG       -0.112126    0.0        0.0
1  ABHD14A       -0.079795    0.0        0.0
      gene  logfoldchanges  pval  MAST_adj_pval
0     A1BG       -0.112126   0.0            0.0
1  ABHD14A       -0.079795   0.0            0.0
2     ACTB       -0.875591   0.0            0.0
3    ACTG1       -0.127924   0.0            0.0
4  AKAP17A       -0.094034   0.0            0.0

In [9]:
df_MAST.head(2)

      gene  logfoldchanges  pval  MAST_adj_pval
0     A1BG       -0.112126   0.0            0.0
1  ABHD14A       -0.079795   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [10]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    # df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 4)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  MAST_adj_pval
0    5S_rRNA-2                1.0                  1.0            1.0
1    5S_rRNA-5                1.0                  1.0            1.0
2    5_8S_rRNA                1.0                  1.0            1.0
3  5_8S_rRNA-1                1.0                  1.0            1.0
4  5_8S_rRNA-2                1.0                  1.0            1.0

In [11]:
df_mmm.head(2)

        gene  Wilcoxon_adj_pval  limmatrend_adj_pval  MAST_adj_pval
0  5S_rRNA-2                1.0                  1.0            1.0
1  5S_rRNA-5                1.0                  1.0            1.0

In [12]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

# df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
#     .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', #'rank_RISCQP', 
     'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_MAST,rank_sum
0,JUND,0.0,0.0,0.0,1,1,1,3
1,JUNB,0.0,0.0,0.0,1,1,1,3
2,TECR,0.0,0.0,0.0,1,1,1,3
3,MT-ND4L,0.0,0.0,0.0,1,1,1,3
4,MT-ND2,0.0,0.0,0.0,1,1,1,3
...,...,...,...,...,...,...,...,...
28471,5_8S_rRNA,1.0,1.0,1.0,8878,25716,25354,59948
28472,5S_rRNA-5,1.0,1.0,1.0,8878,25716,25354,59948
28473,hsa-mir-8069-1,1.0,1.0,1.0,8878,25716,25354,59948
28474,5S_rRNA-2,1.0,1.0,1.0,8878,25716,25354,59948
28475,5_8S_rRNA-8,1.0,1.0,1.0,8878,25716,25354,59948

In [13]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', #'rank_RISCQP', 
                    'rank_MAST']]
df_mmm_re.head(20)

    rank_sum      gene  rank_wilcoxon  rank_limma  rank_MAST
0          3      JUND              1           1          1
1          3      JUNB              1           1          1
2          3      TECR              1           1          1
3          3   MT-ND4L              1           1          1
4          3    MT-ND2              1           1          1
5          3    MT-ND1              1           1          1
6          3    MT-CYB              1           1          1
7          3    MT-CO3              1           1          1
8          3    MT-ND3              1           1          1
9          3     UBA52              1           1          1
10         3     RPS26              1           1          1
11         3     RPS25              1           1          1
12         3     RPS23              1           1          1
13         3    MT-ND5              1           1          1
14         3    MT-ND6              1           1          1
15         3     RPS29              1           1          1
16         3    COX6A1              1           1          1
17         3    KDELR1              1           1          1
18         3  C12orf57              1           1          1
19         3      ATF4              1           1          1

In [14]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum             gene  rank_wilcoxon  rank_limma  rank_MAST  \
64         3  ENSG00000255508              1           1          1
65         3          NDUFA11              1           1          1
66         3             LSP1              1           1          1
67         3     SENP3-EIF4A1              1           1          1
3          3          MT-ND4L              1           1          1
2          3             TECR              1           1          1
1          3             JUNB              1           1          1
0          3             JUND              1           1          1
55         3             ACTB              1           1          1
62         3              MIF              1           1          1
61         3            RPL13              1           1          1
60         3            RPL23              1           1          1
59         3            RPL14              1           1          1
58         3             MCL1              1           1          1
57         3           RPL13A              1           1          1
56         3   BLOC1S5-TXNDC5              1           1          1
9          3            UBA52              1           1          1
10         3            RPS26              1           1          1
11         3            RPS25              1           1          1
28         3           S100A6              1           1          1

   Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
64           MSS         MSS         MSS       MSS  MSS_high
65           MSI         MSI         MSI       MSI  MSI_high
66           MSI         MSI         MSI       MSI  MSI_high
67           MSS         MSS         MSI       MSS  MSS_high
3            MSI         MSI         MSI       MSI  MSI_high
2            MSI         MSI         MSI       MSI  MSI_high
1            MSI         MSI         MSS       MSI  MSI_high
0            MSS         MSS         MSS       MSS  MSS_high
55           MSI         MSI         MSI       MSI  MSI_high
62           MSI         MSI         MSI       MSI  MSI_high
61           MSI         MSI         MSI       MSI  MSI_high
60           MSS         MSS         MSS       MSS  MSS_high
59           MSI         MSI         MSI       MSI  MSI_high
58           MSS         MSS         MSS       MSS  MSS_high
57           MSS         MSS         MSI       MSS  MSS_high
56           MSS         MSS         MSI       MSS  MSS_high
9            MSI         MSI         MSI       MSI  MSI_high
10           MSI         MSI         MSI       MSI  MSI_high
11           MSI         MSI         MSI       MSI  MSI_high
28           MSI         MSI         MSI       MSI  MSI_high

In [15]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,3,JUND,1,1,1,MSS,MSS,MSS,MSS,MSS_high
1,3,JUNB,1,1,1,MSI,MSI,MSS,MSI,MSI_high
2,3,TECR,1,1,1,MSI,MSI,MSI,MSI,MSI_high
3,3,MT-ND4L,1,1,1,MSI,MSI,MSI,MSI,MSI_high
4,3,MT-ND2,1,1,1,MSI,MSI,MSI,MSI,MSI_high
5,3,MT-ND1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
6,3,MT-CYB,1,1,1,MSI,MSI,MSI,MSI,MSI_high
7,3,MT-CO3,1,1,1,MSI,MSI,MSI,MSI,MSI_high
8,3,MT-ND3,1,1,1,MSI,MSI,MSI,MSI,MSI_high
9,3,UBA52,1,1,1,MSI,MSI,MSI,MSI,MSI_high
10,3,RPS26,1,1,1,MSI,MSI,MSI,MSI,MSI_high
11,3,RPS25,1,1,1,MSI,MSI,MSI,MSI,MSI_high
12,3,RPS23,1,1,1,MSI,MSI,MSI,MSI,MSI_high
13,3,MT-ND5,1,1,1,MSI,MSI,MSI,MSI,MSI_high
14,3,MT-ND6,1,1,1,MSI,MSI,MSI,MSI,MSI_high
15,3,RPS29,1,1,1,MSS,MSS,MSS,MSS,MSS_high
16,3,COX6A1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
17,3,KDELR1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
18,3,C12orf57,1,1,1,MSI,MSI,MSI,MSI,MSI_high
19,3,ATF4,1,1,1,MSS,MSS,MSS,MSS,MSS_high

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,44009,8878,18508,16623,MSI,MSS,MSS,MSI,MSS_high
1,LYVE1,37928,8878,8043,21007,MSS,MSS,MSS,MSS,MSS_high
2,CLEC5A,53802,8878,19570,25354,MSS,MSS,MSS,MSS,MSS_high
3,CX3CR1,39662,8878,17731,13053,MSI,MSS,MSI,MSI,MSI_high
4,FN1,16071,7130,4532,4409,MSI,MSS,MSS,MSI,MSS_high
5,IL11,23432,8878,1722,12832,MSI,MSI,MSS,MSI,MSI_high
6,NRAP,43931,8878,15906,19147,MSS,MSS,NaN,MSS,MSS_high
7,SDC1,35880,8878,24198,2804,MSS,MSI,MSS,MSS,MSS_high
8,SCG5,35989,8878,8713,18398,MSS,MSS,MSI,MSS,MSS_high

In [18]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', #'rank_RISCQP', 
             'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,44009,8878,18508,16623,MSI,MSS,MSS,MSI,MSS_high,14670
1,LYVE1,37928,8878,8043,21007,MSS,MSS,MSS,MSS,MSS_high,12643
2,CLEC5A,53802,8878,19570,25354,MSS,MSS,MSS,MSS,MSS_high,17934
3,CX3CR1,39662,8878,17731,13053,MSI,MSS,MSI,MSI,MSI_high,13221
4,FN1,16071,7130,4532,4409,MSI,MSS,MSS,MSI,MSS_high,5357
5,IL11,23432,8878,1722,12832,MSI,MSI,MSS,MSI,MSI_high,7811
6,NRAP,43931,8878,15906,19147,MSS,MSS,NaN,MSS,MSS_high,14644
7,SDC1,35880,8878,24198,2804,MSS,MSI,MSS,MSS,MSS_high,11960
8,SCG5,35989,8878,8713,18398,MSS,MSS,MSI,MSS,MSS_high,11996