In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [1]:
import pandas as pd
import numpy as np

### 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Epithelial_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names     scores  logfoldchanges          pvals      pvals_adj
0  MT-ND4L  48.241734        3.637189   0.000000e+00   0.000000e+00
1  MT-ATP8  46.419098        3.875587   0.000000e+00   0.000000e+00
2   MT-ND6  36.489178        3.291033  1.646604e-291  1.562956e-287
3   MT-CO2  34.175087        2.794080  5.670646e-256  4.036933e-252
4   MT-CO1  33.537945        2.749732  1.349542e-246  7.685912e-243
      gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  MT-ND4L        3.637189   0.000000e+00       0.000000e+00
1  MT-ATP8        3.875587   0.000000e+00       0.000000e+00
2   MT-ND6        3.291033  1.646604e-291      1.562956e-287
3   MT-CO2        2.794080  5.670646e-256      4.036933e-252
4   MT-CO1        2.749732  1.349542e-246      7.685912e-243

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        3.637189   0.0                0.0
1  MT-ATP8        3.875587   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_epithelial_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 6)
     names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0   MT-ND6  1.976472e-277  5.628201e-273       -1.325078       276.704109
1  MT-ND4L  1.223341e-248  1.741793e-244       -1.578009       247.912452

   neglog10_adjpvalue
0          272.249630
1          243.759003
     names  logfoldchanges          pvals      pvals_adj
0   MT-ND6       -1.325078  1.976472e-277  5.628201e-273
1  MT-ND4L       -1.578009  1.223341e-248  1.741793e-244
2  MT-ATP8       -1.289127  6.488523e-193  6.158906e-189
3   MT-CYB       -2.049981  1.216166e-151  8.657883e-148
4    MT-TC       -0.292131  6.803969e-150  3.874996e-146
      gene  logfoldchanges           pval  limmatrend_adj_pval
0   MT-ND6       -1.325078  1.976472e-277        5.628201e-273
1  MT-ND4L       -1.578009  1.223341e-248        1.741793e-244
2  MT-ATP8       -1.289127  6.488523e-193        6.158906e-189
3   MT-CYB       -2.049981  1.216166e-151        8.657883e-148
4    MT-TC       -0.292131  6.803969e-150        3.874996e-146

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges           pval  limmatrend_adj_pval
0   MT-ND6       -1.325078  1.976472e-277        5.628201e-273
1  MT-ND4L       -1.578009  1.223341e-248        1.741793e-244

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_Epithelial_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(20025, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0    MT-ATP8  MT-ATP8    0.569    0.322    0.954    7.192256    2.179936
1    MT-ND4L  MT-ND4L    0.634    0.412    0.982    7.595174    2.859519
2     MT-ND6   MT-ND6    0.480    0.274    0.801    5.715621    1.758046
3     MT-CO2   MT-CO2    0.708    0.525    0.995    8.095858    4.219691
4     MT-CYB   MT-CYB    0.710    0.529    0.993    8.033145    4.209979

     log2FC         Pvalue           Padj
0 -7.403238   0.000000e+00   0.000000e+00
1 -6.916504   0.000000e+00   0.000000e+00
2 -5.977776  2.816179e-272  1.879799e-268
3 -5.613058  5.614299e-246  2.810658e-242
4 -5.536773  3.526976e-244  1.412554e-240
      gene    log2FC           pval  RISCQP_adj_pval
0  MT-ATP8 -7.403238   0.000000e+00     0.000000e+00
1  MT-ND4L -6.916504   0.000000e+00     0.000000e+00
2   MT-ND6 -5.977776  2.816179e-272    1.879799e-268
3   MT-CO2 -5.613058  5.614299e-246    2.810658e-242
4   MT-CYB -5.536773  3.526976e-244    1.412554e-240

In [7]:
df_RISCQP.head(2)

      gene    log2FC  pval  RISCQP_adj_pval
0  MT-ATP8 -7.403238   0.0              0.0
1  MT-ND4L -6.916504   0.0              0.0

In [8]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_Epithelial.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
     names  logfoldchanges  pvals  pvals_adj
0  MT-ATP6       -1.194524    0.0        0.0
1  MT-ATP8       -1.764393    0.0        0.0
      gene  logfoldchanges  pval  MAST_adj_pval
0  MT-ATP6       -1.194524   0.0            0.0
1  MT-ATP8       -1.764393   0.0            0.0
2   MT-CO1       -2.430887   0.0            0.0
3   MT-CO2       -2.245587   0.0            0.0
4   MT-CO3       -1.823035   0.0            0.0

In [9]:
df_MAST.head(2)

      gene  logfoldchanges  pval  MAST_adj_pval
0  MT-ATP6       -1.194524   0.0            0.0
1  MT-ATP8       -1.764393   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [10]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [11]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [12]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,MT-ND4L,0.000000e+00,1.741793e-244,0.000000e+00,0.0,1,2,1,1,5
1,MT-ATP8,0.000000e+00,6.158906e-189,0.000000e+00,0.0,1,3,1,1,6
2,MT-ND6,1.562956e-287,5.628201e-273,1.879799e-268,0.0,3,1,3,1,8
3,MT-CO2,4.036933e-252,2.086402e-144,2.810658e-242,0.0,4,6,4,1,15
4,MT-CYB,4.385797e-231,8.657883e-148,1.412554e-240,0.0,8,4,5,1,18
...,...,...,...,...,...,...,...,...,...,...
28471,PRKD3-DT,1.000000e+00,1.000000e+00,NaN,1.0,7161,21286,20026,22486,70959
28472,PRL,1.000000e+00,1.000000e+00,NaN,1.0,7161,21286,20026,22486,70959
28473,PRLHR,1.000000e+00,1.000000e+00,NaN,1.0,7161,21286,20026,22486,70959
28474,PRM1,1.000000e+00,1.000000e+00,NaN,1.0,7161,21286,20026,22486,70959
28475,ZSWIM2,1.000000e+00,1.000000e+00,NaN,1.0,7161,21286,20026,22486,70959

In [13]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0          5  MT-ND4L              1           2            1          1
1          6  MT-ATP8              1           3            1          1
2          8   MT-ND6              3           1            3          1
3         15   MT-CO2              4           6            4          1
4         18   MT-CYB              8           4            5          1
5         19   MT-CO1              5           7            6          1
6         35    RPL17              7           8            7         13
7         46   MT-CO3             21          14           10          1
8         52   MT-ND1             25          18            8          1
9         54   MT-ND5              9          20           11         14
10        68   MT-ND3             28          30            9          1
11        72    RPL26             12          24           18         18
12        77    CRIP1             20          26           16         15
13       104    RPL39             13          47           23         21
14       114  MT-ATP6             67          33           13          1
15       122    RPL13             14          29           50         29
16       141   MT-ND4             67          59           14          1
17       145   MT-ND2             56          76           12          1
18       148    RPL15             30          46           34         38
19       162    RPL28              6         109           31         16

In [14]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
0          5  MT-ND4L              1           2            1          1
1          6  MT-ATP8              1           3            1          1
2          8   MT-ND6              3           1            3          1
3         15   MT-CO2              4           6            4          1
4         18   MT-CYB              8           4            5          1
5         19   MT-CO1              5           7            6          1
6         35    RPL17              7           8            7         13
7         46   MT-CO3             21          14           10          1
8         52   MT-ND1             25          18            8          1
9         54   MT-ND5              9          20           11         14
10        68   MT-ND3             28          30            9          1
11        72    RPL26             12          24           18         18
12        77    CRIP1             20          26           16         15
13       104    RPL39             13          47           23         21
14       114  MT-ATP6             67          33           13          1
15       122    RPL13             14          29           50         29
16       141   MT-ND4             67          59           14          1
17       145   MT-ND2             56          76           12          1
18       148    RPL15             30          46           34         38
19       162    RPL28              6         109           31         16

   Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
0            MSI         MSI         MSI       MSI  MSI_high
1            MSI         MSI         MSI       MSI  MSI_high
2            MSI         MSI         MSI       MSI  MSI_high
3            MSI         MSI         MSI       MSI  MSI_high
4            MSI         MSI         MSI       MSI  MSI_high
5            MSI         MSI         MSI       MSI  MSI_high
6            MSI         MSI         MSI       MSI  MSI_high
7            MSI         MSI         MSI       MSI  MSI_high
8            MSI         MSI         MSI       MSI  MSI_high
9            MSI         MSI         MSI       MSI  MSI_high
10           MSI         MSI         MSI       MSI  MSI_high
11           MSI         MSI         MSI       MSI  MSI_high
12           MSI         MSI         MSI       MSI  MSI_high
13           MSI         MSI         MSI       MSI  MSI_high
14           MSI         MSI         MSI       MSI  MSI_high
15           MSI         MSI         MSI       MSI  MSI_high
16           MSI         MSI         MSI       MSI  MSI_high
17           MSI         MSI         MSI       MSI  MSI_high
18           MSI         MSI         MSI       MSI  MSI_high
19           MSI         MSI         MSI       MSI  MSI_high

In [15]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,5,MT-ND4L,1,2,1,1,MSI,MSI,MSI,MSI,MSI_high
1,6,MT-ATP8,1,3,1,1,MSI,MSI,MSI,MSI,MSI_high
2,8,MT-ND6,3,1,3,1,MSI,MSI,MSI,MSI,MSI_high
3,15,MT-CO2,4,6,4,1,MSI,MSI,MSI,MSI,MSI_high
4,18,MT-CYB,8,4,5,1,MSI,MSI,MSI,MSI,MSI_high
5,19,MT-CO1,5,7,6,1,MSI,MSI,MSI,MSI,MSI_high
6,35,RPL17,7,8,7,13,MSI,MSI,MSI,MSI,MSI_high
7,46,MT-CO3,21,14,10,1,MSI,MSI,MSI,MSI,MSI_high
8,52,MT-ND1,25,18,8,1,MSI,MSI,MSI,MSI,MSI_high
9,54,MT-ND5,9,20,11,14,MSI,MSI,MSI,MSI,MSI_high
10,68,MT-ND3,28,30,9,1,MSI,MSI,MSI,MSI,MSI_high
11,72,RPL26,12,24,18,18,MSI,MSI,MSI,MSI,MSI_high
12,77,CRIP1,20,26,16,15,MSI,MSI,MSI,MSI,MSI_high
13,104,RPL39,13,47,23,21,MSI,MSI,MSI,MSI,MSI_high
14,114,MT-ATP6,67,33,13,1,MSI,MSI,MSI,MSI,MSI_high
15,122,RPL13,14,29,50,29,MSI,MSI,MSI,MSI,MSI_high
16,141,MT-ND4,67,59,14,1,MSI,MSI,MSI,MSI,MSI_high
17,145,MT-ND2,56,76,12,1,MSI,MSI,MSI,MSI,MSI_high
18,148,RPL15,30,46,34,38,MSI,MSI,MSI,MSI,MSI_high
19,162,RPL28,6,109,31,16,MSI,MSI,MSI,MSI,MSI_high

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,62968,7161,18235,20026,17546,MSI,MSI,NaN,MSI,MSI_high
1,LYVE1,61001,7161,18359,20026,15455,MSS,MSS,NaN,MSS,MSS_high
2,CLEC5A,52075,7161,8773,20026,16115,MSI,MSI,NaN,MSS,MSS_high
3,CX3CR1,67974,7161,18301,20026,22486,MSS,MSS,NaN,MSS,MSS_high
4,FN1,21617,4856,8773,4195,3793,MSI,MSI,MSI,MSI,MSI_high
5,IL11,59742,7161,17734,14359,20488,MSS,MSS,MSS,MSS,MSS_high
6,NRAP,49010,7161,5781,17554,18514,MSI,MSI,MSI,MSI,MSI_high
7,SDC1,15425,2618,6799,3390,2618,MSS,MSS,MSS,MSS,MSS_high
8,SCG5,50820,7161,7374,15894,20391,MSS,MSI,MSS,MSS,MSS_high

In [17]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,62968,7161,18235,20026,17546,MSI,MSI,NaN,MSI,MSI_high,15742
1,LYVE1,61001,7161,18359,20026,15455,MSS,MSS,NaN,MSS,MSS_high,15250
2,CLEC5A,52075,7161,8773,20026,16115,MSI,MSI,NaN,MSS,MSS_high,13019
3,CX3CR1,67974,7161,18301,20026,22486,MSS,MSS,NaN,MSS,MSS_high,16994
4,FN1,21617,4856,8773,4195,3793,MSI,MSI,MSI,MSI,MSI_high,5404
5,IL11,59742,7161,17734,14359,20488,MSS,MSS,MSS,MSS,MSS_high,14936
6,NRAP,49010,7161,5781,17554,18514,MSI,MSI,MSI,MSI,MSI_high,12252
7,SDC1,15425,2618,6799,3390,2618,MSS,MSS,MSS,MSS,MSS_high,3856
8,SCG5,50820,7161,7374,15894,20391,MSS,MSI,MSS,MSS,MSS_high,12705