In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [1]:
import pandas as pd
import numpy as np

### 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Bcell_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names      scores  logfoldchanges  pvals  pvals_adj
0  PTPRCAP  135.248150        5.784529    0.0        0.0
1  MT-ATP8  123.874405        3.806541    0.0        0.0
2     CD74  123.015730        0.566575    0.0        0.0
3  MT-ND4L  110.497930        2.406979    0.0        0.0
4    EEF1G   96.309060        3.170278    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  PTPRCAP        5.784529   0.0                0.0
1  MT-ATP8        3.806541   0.0                0.0
2     CD74        0.566575   0.0                0.0
3  MT-ND4L        2.406979   0.0                0.0
4    EEF1G        3.170278   0.0                0.0

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  PTPRCAP        5.784529   0.0                0.0
1  MT-ATP8        3.806541   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_B_cell_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 4)
   names  pvals  pvals_adj  logfoldchanges
0  RPS10    0.0        0.0        1.714055
1   CD74    0.0        0.0       -1.498023
     names  logfoldchanges  pvals  pvals_adj
0    RPS10        1.714055    0.0        0.0
1     CD74       -1.498023    0.0        0.0
2  PTPRCAP       -1.267538    0.0        0.0
3     JUND        1.827575    0.0        0.0
4  MT-ATP8       -1.212474    0.0        0.0
      gene  logfoldchanges  pval  limmatrend_adj_pval
0    RPS10        1.714055   0.0                  0.0
1     CD74       -1.498023   0.0                  0.0
2  PTPRCAP       -1.267538   0.0                  0.0
3     JUND        1.827575   0.0                  0.0
4  MT-ATP8       -1.212474   0.0                  0.0

In [5]:
df_limmatrend.head(2)

    gene  logfoldchanges  pval  limmatrend_adj_pval
0  RPS10        1.714055   0.0                  0.0
1   CD74       -1.498023   0.0                  0.0

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_b_cell_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(20128, 10)
  Unnamed: 0    Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      RPL22     RPL22    0.894    0.817    0.982    7.312864    6.063652
1      RUNX3     RUNX3    0.171    0.257    0.072    0.462783    1.699150
2   SH3BGRL3  SH3BGRL3    0.692    0.573    0.830    5.810756    3.919092
3        JUN       JUN    0.651    0.753    0.532    3.699936    5.481283
4     ATP5PB    ATP5PB    0.294    0.204    0.399    2.613024    1.308258

     log2FC  Pvalue  Padj
0 -1.804630     0.0   0.0
1  2.924962     0.0   0.0
2 -2.753706     0.0   0.0
3  2.600040     0.0   0.0
4 -2.227141     0.0   0.0
       gene    log2FC  pval  RISCQP_adj_pval
0     RPL22 -1.804630   0.0              0.0
1     RUNX3  2.924962   0.0              0.0
2  SH3BGRL3 -2.753706   0.0              0.0
3       JUN  2.600040   0.0              0.0
4    ATP5PB -2.227141   0.0              0.0

In [7]:
df_RISCQP.head(2)

    gene    log2FC  pval  RISCQP_adj_pval
0  RPL22 -1.804630   0.0              0.0
1  RUNX3  2.924962   0.0              0.0

In [8]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_B_cell.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
  names  logfoldchanges  pvals  pvals_adj
0  ACTB       -1.058832    0.0        0.0
1   ADK       -0.216600    0.0        0.0
     gene  logfoldchanges  pval  MAST_adj_pval
0    ACTB       -1.058832   0.0            0.0
1     ADK       -0.216600   0.0            0.0
2    AFF3       -0.298353   0.0            0.0
3   ALDOA       -0.199907   0.0            0.0
4  ALYREF        0.066442   0.0            0.0

In [9]:
df_MAST.head(2)

   gene  logfoldchanges  pval  MAST_adj_pval
0  ACTB       -1.058832   0.0            0.0
1   ADK       -0.216600   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [10]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [11]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [12]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,IGHA2,0.0,0.0,0.0,0.0,1,1,1,1,4
1,IGHA1,0.0,0.0,0.0,0.0,1,1,1,1,4
2,SYNGR2,0.0,0.0,0.0,0.0,1,1,1,1,4
3,CNBP,0.0,0.0,0.0,0.0,1,1,1,1,4
4,DUSP1,0.0,0.0,0.0,0.0,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...
28471,5_8S_rRNA,1.0,1.0,NaN,1.0,8445,23227,20129,23241,75042
28472,5S_rRNA-5,1.0,1.0,NaN,1.0,8445,23227,20129,23241,75042
28473,hsa-mir-8069-1,1.0,1.0,NaN,1.0,8445,23227,20129,23241,75042
28474,5S_rRNA-2,1.0,1.0,NaN,1.0,8445,23227,20129,23241,75042
28475,ZSWIM2,1.0,1.0,NaN,1.0,8445,23227,20129,23241,75042

In [13]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum      gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0          4     IGHA2              1           1            1          1
1          4     IGHA1              1           1            1          1
2          4    SYNGR2              1           1            1          1
3          4      CNBP              1           1            1          1
4          4     DUSP1              1           1            1          1
5          4     DUSP2              1           1            1          1
6          4      LSP1              1           1            1          1
7          4       LTB              1           1            1          1
8          4     FCER2              1           1            1          1
9          4     EEF1G              1           1            1          1
10         4     EEF1D              1           1            1          1
11         4     FCRLA              1           1            1          1
12         4  SH3BGRL3              1           1            1          1
13         4     SRSF3              1           1            1          1
14         4    ATP1B3              1           1            1          1
15         4      CNN2              1           1            1          1
16         4   MT-ATP8              1           1            1          1
17         4     HCLS1              1           1            1          1
18         4      RAC2              1           1            1          1
19         4     IGLC2              1           1            1          1

In [14]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

     rank_sum      gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
128         4    COX4I1              1           1            1          1
129         4      MIDN              1           1            1          1
130         4      CD74              1           1            1          1
131         4      CD69              1           1            1          1
132         4     RPLP0              1           1            1          1
133         4  HLA-DPA1              1           1            1          1
134         4    COX6A1              1           1            1          1
135         4     RBM38              1           1            1          1
136         4    TAGLN2              1           1            1          1
137         4     UBE2S              1           1            1          1
138         4     BASP1              1           1            1          1
139         4     MS4A1              1           1            1          1
140         4    ZNF331              1           1            1          1
141         4    PPP1CA              1           1            1          1
2           4    SYNGR2              1           1            1          1
1           4     IGHA1              1           1            1          1
70          4   GABARAP              1           1            1          1
69          4      CD83              1           1            1          1
68          4    RNASEK              1           1            1          1
67          4     CD79B              1           1            1          1

    Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
128           MSI         MSI         MSI       MSI  MSI_high
129           MSS         MSS         MSS       MSS  MSS_high
130           MSI         MSI         MSI       MSI  MSI_high
131           MSS         MSS         MSS       MSS  MSS_high
132           MSI         MSI         MSI       MSI  MSI_high
133           MSI         MSI         MSI       MSI  MSI_high
134           MSI         MSI         MSI       MSI  MSI_high
135           MSS         MSS         MSS       MSS  MSS_high
136           MSI         MSI         MSI       MSI  MSI_high
137           MSS         MSS         MSS       MSS  MSS_high
138           MSS         MSS         MSS       MSS  MSS_high
139           MSI         MSI         MSI       MSI  MSI_high
140           MSS         MSS         MSS       MSS  MSS_high
141           MSI         MSI         MSI       MSI  MSI_high
2             MSI         MSI         MSI       MSI  MSI_high
1             MSS         MSS         MSS       MSS  MSS_high
70            MSI         MSI         MSI       MSI  MSI_high
69            MSS         MSS         MSS       MSS  MSS_high
68            MSI         MSI         MSI       MSI  MSI_high
67            MSI         MSI         MSI       MSI  MSI_high

In [15]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,4,IGHA2,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
1,4,IGHA1,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
2,4,SYNGR2,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
3,4,CNBP,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
4,4,DUSP1,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
5,4,DUSP2,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
6,4,LSP1,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
7,4,LTB,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
8,4,FCER2,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
9,4,EEF1G,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
10,4,EEF1D,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
11,4,FCRLA,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
12,4,SH3BGRL3,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
13,4,SRSF3,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
14,4,ATP1B3,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
15,4,CNN2,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
16,4,MT-ATP8,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
17,4,HCLS1,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
18,4,RAC2,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
19,4,IGLC2,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,37051,8445,9284,9935,9387,MSS,MSS,MSS,MSS,MSS_high
1,LYVE1,53691,8445,14057,14683,16506,MSS,MSS,MSS,MSS,MSS_high
2,CLEC5A,52812,8445,15594,13340,15433,MSS,MSS,MSS,MSS,MSS_high
3,CX3CR1,24726,8445,5067,6487,4727,MSI,MSI,MSI,MSI,MSI_high
4,FN1,27702,8280,7108,5994,6320,MSS,MSS,MSS,MSS,MSS_high
5,IL11,56051,8445,14665,16757,16184,MSS,MSS,MSS,MSS,MSS_high
6,NRAP,68044,8445,19435,20129,20035,MSS,MSS,NaN,MSS,MSS_high
7,SDC1,28346,8445,7667,6496,5738,MSS,MSS,MSS,MSS,MSS_high
8,SCG5,53037,8445,12868,18921,12803,MSS,MSS,MSI,MSS,MSS_high

In [17]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,37051,8445,9284,9935,9387,MSS,MSS,MSS,MSS,MSS_high,9263
1,LYVE1,53691,8445,14057,14683,16506,MSS,MSS,MSS,MSS,MSS_high,13423
2,CLEC5A,52812,8445,15594,13340,15433,MSS,MSS,MSS,MSS,MSS_high,13203
3,CX3CR1,24726,8445,5067,6487,4727,MSI,MSI,MSI,MSI,MSI_high,6182
4,FN1,27702,8280,7108,5994,6320,MSS,MSS,MSS,MSS,MSS_high,6926
5,IL11,56051,8445,14665,16757,16184,MSS,MSS,MSS,MSS,MSS_high,14013
6,NRAP,68044,8445,19435,20129,20035,MSS,MSS,NaN,MSS,MSS_high,17011
7,SDC1,28346,8445,7667,6496,5738,MSS,MSS,MSS,MSS,MSS_high,7086
8,SCG5,53037,8445,12868,18921,12803,MSS,MSS,MSI,MSS,MSS_high,13259