In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [39]:
import pandas as pd
import numpy as np

### 데이터 정제

In [40]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_random10_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
    names     scores  logfoldchanges          pvals      pvals_adj
0  RPL13A  28.330397        2.672939  1.459844e-176  4.157051e-172
1   RPS11  27.693296        2.192736  8.408641e-169  1.197222e-164
2    RPS2  26.615640        2.582640  4.474600e-156  4.247290e-152
3   RPS10  25.069100        5.119965  1.080962e-138  3.847684e-135
4   RPS20  23.610120        2.750181  3.033728e-123  7.853493e-120
     gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  RPL13A        2.672939  1.459844e-176      4.157051e-172
1   RPS11        2.192736  8.408641e-169      1.197222e-164
2    RPS2        2.582640  4.474600e-156      4.247290e-152
3   RPS10        5.119965  1.080962e-138      3.847684e-135
4   RPS20        2.750181  3.033728e-123      7.853493e-120

In [41]:
df_wilcoxon.head(2)

     gene  logfoldchanges           pval  Wilcoxon_adj_pval
0  RPL13A        2.672939  1.459844e-176      4.157051e-172
1   RPS11        2.192736  8.408641e-169      1.197222e-164

In [42]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_random10_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 6)
     names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0    RPS10  4.940656e-324  4.940656e-324       -1.376256              NaN
1  MT-RNR1  8.971655e-269  1.277384e-264       -1.149125       268.047127

   neglog10_adjpvalue
0                 NaN
1          263.893678
     names  logfoldchanges          pvals      pvals_adj
0    RPS10       -1.376256  4.940656e-324  4.940656e-324
1  MT-RNR1       -1.149125  8.971655e-269  1.277384e-264
2  HLA-DRA       -1.089754  4.159185e-221  3.947898e-217
3    FCGBP       -1.066850  1.266492e-219  9.016160e-216
4     MUC2       -1.078457  5.780723e-195  3.292238e-191
      gene  logfoldchanges           pval  limmatrend_adj_pval
0    RPS10       -1.376256  4.940656e-324        4.940656e-324
1  MT-RNR1       -1.149125  8.971655e-269        1.277384e-264
2  HLA-DRA       -1.089754  4.159185e-221        3.947898e-217
3    FCGBP       -1.066850  1.266492e-219        9.016160e-216
4     MUC2       -1.078457  5.780723e-195        3.292238e-191

In [43]:
df_limmatrend.head(2)

      gene  logfoldchanges           pval  limmatrend_adj_pval
0    RPS10       -1.376256  4.940656e-324        4.940656e-324
1  MT-RNR1       -1.149125  8.971655e-269        1.277384e-264

In [44]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_random10_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(20979, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0      RPS10    RPS10    0.409    0.296    0.758    4.950142    1.399180
1    ATP6V0C  ATP6V0C    0.691    0.842    0.226    1.346178    5.053406
2       NME2     NME2    0.763    0.885    0.386    2.353214    5.899967
3       CD24     CD24    0.686    0.832    0.239    1.551672    5.443116
4      FCGBP    FCGBP    0.226    0.119    0.557    3.626929    0.581330

     log2FC         Pvalue           Padj
0 -5.521594  5.117011e-160  1.073498e-155
1  5.774012  3.557956e-150  3.732118e-146
2  5.257037  2.144474e-140  1.499631e-136
3  5.951449  9.896132e-139  5.190274e-135
4 -5.536632  2.875509e-130  1.206506e-126
      gene    log2FC           pval  RISCQP_adj_pval
0    RPS10 -5.521594  5.117011e-160    1.073498e-155
1  ATP6V0C  5.774012  3.557956e-150    3.732118e-146
2     NME2  5.257037  2.144474e-140    1.499631e-136
3     CD24  5.951449  9.896132e-139    5.190274e-135
4    FCGBP -5.536632  2.875509e-130    1.206506e-126

In [45]:
df_RISCQP.head(2)

      gene    log2FC           pval  RISCQP_adj_pval
0    RPS10 -5.521594  5.117011e-160    1.073498e-155
1  ATP6V0C  5.774012  3.557956e-150    3.732118e-146

In [46]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_random10.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
    names  logfoldchanges          pvals      pvals_adj
0   RPS10       -0.864798   0.000000e+00   0.000000e+00
1  RPL13A       -1.308700  1.529150e-276  2.177204e-272
      gene  logfoldchanges           pval  MAST_adj_pval
0    RPS10       -0.864798   0.000000e+00   0.000000e+00
1   RPL13A       -1.308700  1.529150e-276  2.177204e-272
2    RPS11       -0.925364  4.013311e-264  3.809434e-260
3  MT-ND4L        0.836951  3.962470e-263  2.820882e-259
4     AGR2       -0.931461  1.136514e-246  6.472673e-243

In [47]:
df_MAST.head(2)

     gene  logfoldchanges           pval  MAST_adj_pval
0   RPS10       -0.864798   0.000000e+00   0.000000e+00
1  RPL13A       -1.308700  1.529150e-276  2.177204e-272

## <font color="red">**MSS/MSI 데이터프레임**

In [48]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [49]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [50]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,RPS10,3.847684e-135,4.940656e-324,1.073498e-155,0.000000e+00,8,1,1,1,11
1,ATP6V0C,6.179719e-147,6.830477e-184,3.732118e-146,2.027003e-193,4,6,2,11,23
2,CD24,2.879574e-139,1.292467e-154,5.190274e-135,1.777199e-182,5,12,4,15,36
3,HLA-DRA,3.986633e-93,3.947898e-217,1.397982e-126,5.945997e-158,26,3,6,17,52
4,NME2,7.132897e-108,1.072216e-147,1.499631e-136,4.286425e-144,14,15,3,22,54
...,...,...,...,...,...,...,...,...,...,...
28471,5_8S_rRNA,1.000000e+00,1.000000e+00,NaN,1.000000e+00,11837,23264,20980,23778,79859
28472,5S_rRNA-5,1.000000e+00,1.000000e+00,NaN,1.000000e+00,11837,23264,20980,23778,79859
28473,hsa-mir-8069-1,1.000000e+00,1.000000e+00,NaN,1.000000e+00,11837,23264,20980,23778,79859
28474,5S_rRNA-2,1.000000e+00,1.000000e+00,NaN,1.000000e+00,11837,23264,20980,23778,79859
28475,ZSWIM2,1.000000e+00,1.000000e+00,NaN,1.000000e+00,11837,23264,20980,23778,79859

In [51]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0         11    RPS10              8           1            1          1
1         23  ATP6V0C              4           6            2         11
2         36     CD24              5          12            4         15
3         52  HLA-DRA             26           3            6         17
4         54     NME2             14          15            3         22
5         57   PABPC1             10           8           12         27
6         71    FCGBP             44           4            5         18
7         72     MUC2             38           5            8         21
8         76     PIGR             32           7            7         30
9         80    RPS20             11          18           39         12
10        87    PPDPF              9          28           26         24
11        95    POLD4             14          22           10         49
12        96   RNASEK             16          27           11         42
13       105   DBNDD2             20          34           19         32
14       108   RPL13A              1          48           57          2
15       109  GABARAP             24          20            9         56
16       127  MT-RNR1             61           2           55          9
17       131    MUC3A             23          41           21         46
18       135    EEF1G             27          36           22         50
19       143  MT-RNR2            103           9           18         13

In [52]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
0         11    RPS10              8           1            1          1
1         23  ATP6V0C              4           6            2         11
2         36     CD24              5          12            4         15
3         52  HLA-DRA             26           3            6         17
4         54     NME2             14          15            3         22
5         57   PABPC1             10           8           12         27
6         71    FCGBP             44           4            5         18
7         72     MUC2             38           5            8         21
8         76     PIGR             32           7            7         30
9         80    RPS20             11          18           39         12
10        87    PPDPF              9          28           26         24
11        95    POLD4             14          22           10         49
12        96   RNASEK             16          27           11         42
13       105   DBNDD2             20          34           19         32
14       108   RPL13A              1          48           57          2
15       109  GABARAP             24          20            9         56
16       127  MT-RNR1             61           2           55          9
17       131    MUC3A             23          41           21         46
18       135    EEF1G             27          36           22         50
19       143  MT-RNR2            103           9           18         13

   Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
0            MSI         MSI         MSI       MSI  MSI_high
1            MSS         MSS         MSS       MSS  MSS_high
2            MSS         MSS         MSS       MSS  MSS_high
3            MSI         MSI         MSI       MSI  MSI_high
4            MSS         MSS         MSS       MSS  MSS_high
5            MSS         MSS         MSS       MSS  MSS_high
6            MSI         MSI         MSI       MSI  MSI_high
7            MSI         MSI         MSI       MSI  MSI_high
8            MSI         MSI         MSI       MSI  MSI_high
9            MSI         MSI         MSI       MSI  MSI_high
10           MSS         MSS         MSS       MSS  MSS_high
11           MSS         MSS         MSS       MSS  MSS_high
12           MSS         MSS         MSS       MSS  MSS_high
13           MSS         MSS         MSS       MSS  MSS_high
14           MSI         MSI         MSI       MSI  MSI_high
15           MSS         MSS         MSS       MSS  MSS_high
16           MSI         MSI         MSI       MSI  MSI_high
17           MSS         MSS         MSS       MSS  MSS_high
18           MSS         MSS         MSS       MSS  MSS_high
19           MSI         MSI         MSI       MSI  MSI_high

In [54]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,11,RPS10,8,1,1,1,MSI,MSI,MSI,MSI,MSI_high
1,23,ATP6V0C,4,6,2,11,MSS,MSS,MSS,MSS,MSS_high
2,36,CD24,5,12,4,15,MSS,MSS,MSS,MSS,MSS_high
3,52,HLA-DRA,26,3,6,17,MSI,MSI,MSI,MSI,MSI_high
4,54,NME2,14,15,3,22,MSS,MSS,MSS,MSS,MSS_high
5,57,PABPC1,10,8,12,27,MSS,MSS,MSS,MSS,MSS_high
6,71,FCGBP,44,4,5,18,MSI,MSI,MSI,MSI,MSI_high
7,72,MUC2,38,5,8,21,MSI,MSI,MSI,MSI,MSI_high
8,76,PIGR,32,7,7,30,MSI,MSI,MSI,MSI,MSI_high
9,80,RPS20,11,18,39,12,MSI,MSI,MSI,MSI,MSI_high
10,87,PPDPF,9,28,26,24,MSS,MSS,MSS,MSS,MSS_high
11,95,POLD4,14,22,10,49,MSS,MSS,MSS,MSS,MSS_high
12,96,RNASEK,16,27,11,42,MSS,MSS,MSS,MSS,MSS_high
13,105,DBNDD2,20,34,19,32,MSS,MSS,MSS,MSS,MSS_high
14,108,RPL13A,1,48,57,2,MSI,MSI,MSI,MSI,MSI_high
15,109,GABARAP,24,20,9,56,MSS,MSS,MSS,MSS,MSS_high
16,127,MT-RNR1,61,2,55,9,MSI,MSI,MSI,MSI,MSI_high
17,131,MUC3A,23,41,21,46,MSS,MSS,MSS,MSS,MSS_high
18,135,EEF1G,27,36,22,50,MSS,MSS,MSS,MSS,MSS_high
19,143,MT-RNR2,103,9,18,13,MSI,MSI,MSI,MSI,MSI_high

In [55]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,55780,11837,14779,12854,16310,MSS,MSS,MSS,MSS,MSS_high
1,LYVE1,29268,11837,3918,6360,7153,MSI,MSI,MSI,MSI,MSI_high
2,CLEC5A,65980,11837,23264,13830,17049,MSS,MSI,MSI,MSS,MSS_high
3,CX3CR1,69450,11837,18030,20980,18603,MSS,MSS,NaN,MSS,MSS_high
4,FN1,31146,6617,9328,7386,7815,MSS,MSS,MSS,MSS,MSS_high
5,IL11,40312,11674,8820,8560,11258,MSS,MSS,MSS,MSS,MSS_high
6,NRAP,48232,11837,9653,11156,15586,MSI,MSI,MSI,MSI,MSI_high
7,SDC1,8001,1308,1665,2019,3009,MSS,MSS,MSS,MSS,MSS_high
8,SCG5,45114,11837,11129,13353,8795,MSI,MSI,MSI,MSI,MSI_high

In [56]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,55780,11837,14779,12854,16310,MSS,MSS,MSS,MSS,MSS_high,13945
1,LYVE1,29268,11837,3918,6360,7153,MSI,MSI,MSI,MSI,MSI_high,7317
2,CLEC5A,65980,11837,23264,13830,17049,MSS,MSI,MSI,MSS,MSS_high,16495
3,CX3CR1,69450,11837,18030,20980,18603,MSS,MSS,NaN,MSS,MSS_high,17362
4,FN1,31146,6617,9328,7386,7815,MSS,MSS,MSS,MSS,MSS_high,7786
5,IL11,40312,11674,8820,8560,11258,MSS,MSS,MSS,MSS,MSS_high,10078
6,NRAP,48232,11837,9653,11156,15586,MSI,MSI,MSI,MSI,MSI_high,12058
7,SDC1,8001,1308,1665,2019,3009,MSS,MSS,MSS,MSS,MSS_high,2000
8,SCG5,45114,11837,11129,13353,8795,MSI,MSI,MSI,MSI,MSI_high,11278