In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [15]:
import pandas as pd
import numpy as np

### 데이터 정제

In [16]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Neutrophil_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names     scores  logfoldchanges  pvals  pvals_adj
0   MT-CO2  55.823940       11.440961    0.0        0.0
1  MT-RNR2  55.691950       14.199527    0.0        0.0
2   MT-CO3  53.859814       11.103656    0.0        0.0
3  MT-RNR1  52.847378       12.605896    0.0        0.0
4  MT-ATP6  50.552143       11.259443    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0   MT-CO2       11.440961   0.0                0.0
1  MT-RNR2       14.199527   0.0                0.0
2   MT-CO3       11.103656   0.0                0.0
3  MT-RNR1       12.605896   0.0                0.0
4  MT-ATP6       11.259443   0.0                0.0

In [17]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0   MT-CO2       11.440961   0.0                0.0
1  MT-RNR2       14.199527   0.0                0.0

In [18]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_neutrophil_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 6)
    names          pvals      pvals_adj  logfoldchanges  neglog10_pvalue  \
0  MT-CYB  4.940656e-324  4.940656e-324       -1.740723              NaN
1  MT-ND2  4.940656e-324  4.940656e-324       -1.697944              NaN

   neglog10_adjpvalue
0                 NaN
1                 NaN
    names  logfoldchanges          pvals      pvals_adj
0  MT-CYB       -1.740723  4.940656e-324  4.940656e-324
1  MT-ND2       -1.697944  4.940656e-324  4.940656e-324
2  MT-ND1       -1.497832  4.940656e-324  4.940656e-324
3   RPLP0       -0.269951  4.940656e-324  4.940656e-324
4  RPL23A       -0.265468  4.940656e-324  4.940656e-324
     gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-CYB       -1.740723  4.940656e-324        4.940656e-324
1  MT-ND2       -1.697944  4.940656e-324        4.940656e-324
2  MT-ND1       -1.497832  4.940656e-324        4.940656e-324
3   RPLP0       -0.269951  4.940656e-324        4.940656e-324
4  RPL23A       -0.265468  4.940656e-324        4.940656e-324

In [19]:
df_limmatrend.head(2)

     gene  logfoldchanges           pval  limmatrend_adj_pval
0  MT-CYB       -1.740723  4.940656e-324        4.940656e-324
1  MT-ND2       -1.697944  4.940656e-324        4.940656e-324

In [20]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_neutrophil_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(14295, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0        FAU      FAU    0.122    0.052    0.540    4.220943    0.395432
1    GABARAP  GABARAP    0.649    0.733    0.148    1.107727    5.808237
2      UBA52    UBA52    0.090    0.038    0.405    3.136310    0.282570
3     IFITM1   IFITM1    0.593    0.665    0.159    1.200478    5.316913
4     RNASEK   RNASEK    0.576    0.648    0.141    1.049693    5.088896

     log2FC         Pvalue           Padj
0 -7.112059   0.000000e+00   0.000000e+00
1  7.355498   0.000000e+00   0.000000e+00
2 -6.075351   0.000000e+00   0.000000e+00
3  6.448401  4.654466e-289  1.663390e-285
4  6.440006  5.651137e-279  1.615660e-275
      gene    log2FC           pval  RISCQP_adj_pval
0      FAU -7.112059   0.000000e+00     0.000000e+00
1  GABARAP  7.355498   0.000000e+00     0.000000e+00
2    UBA52 -6.075351   0.000000e+00     0.000000e+00
3   IFITM1  6.448401  4.654466e-289    1.663390e-285
4   RNASEK  6.440006  5.651137e-279    1.615660e-275

In [21]:
df_RISCQP.head(2)

      gene    log2FC  pval  RISCQP_adj_pval
0      FAU -7.112059   0.0              0.0
1  GABARAP  7.355498   0.0              0.0

In [22]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_neutrophil.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
    names  logfoldchanges  pvals  pvals_adj
0  CCL4L2        1.321031    0.0        0.0
1   CXCL8       -1.200445    0.0        0.0
      gene  logfoldchanges  pval  MAST_adj_pval
0   CCL4L2        1.321031   0.0            0.0
1    CXCL8       -1.200445   0.0            0.0
2      FAU       -0.892780   0.0            0.0
3  GABARAP        1.365931   0.0            0.0
4   IFITM1        1.251028   0.0            0.0

In [23]:
df_MAST.head(2)

     gene  logfoldchanges  pval  MAST_adj_pval
0  CCL4L2        1.321031   0.0            0.0
1   CXCL8       -1.200445   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [24]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [25]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [26]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,MT-ND1,0.0,4.940656e-324,1.618150e-263,0.0,1,1,7,1,10
1,MT-ND2,0.0,4.940656e-324,1.360879e-249,0.0,1,1,8,1,11
2,RPL41,0.0,4.940656e-324,1.074173e-247,0.0,1,1,9,1,12
3,MT-CO3,0.0,4.940656e-324,1.919377e-202,0.0,1,1,11,1,14
4,MT-CO2,0.0,4.940656e-324,8.855409e-191,0.0,1,1,13,1,16
...,...,...,...,...,...,...,...,...,...,...
28471,HEPN1,1.0,1.000000e+00,NaN,1.0,1192,12929,14296,15194,43611
28472,HERC3,1.0,1.000000e+00,NaN,1.0,1192,12929,14296,15194,43611
28473,HES3,1.0,1.000000e+00,NaN,1.0,1192,12929,14296,15194,43611
28474,5_8S_rRNA-3,1.0,1.000000e+00,NaN,1.0,1192,12929,14296,15194,43611
28475,5_8S_rRNA-4,1.0,1.000000e+00,NaN,1.0,1192,12929,14296,15194,43611

In [27]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0         10   MT-ND1              1           1            7          1
1         11   MT-ND2              1           1            8          1
2         12    RPL41              1           1            9          1
3         14   MT-CO3              1           1           11          1
4         16   MT-CO2              1           1           13          1
5         17   MT-ND3              1           1           14          1
6         19   MT-ND4              1           1           16          1
7         20   MT-CYB              1           1           17          1
8         21   MT-CO1              1           1           18          1
9         25  MT-ATP6              1           1           22          1
10        40  MT-RNR1              1           1           37          1
11        74     RPS9             25          42            6          1
12        75    RPL28             22          31           21          1
13        77    RPLP1             23          30           23          1
14        79    RPS28             26          37           15          1
15        79    RPS27             19          29           30          1
16        82  MT-RNR2              1           1           79          1
17        82      FAU             20          60            1          1
18        99    RPL39             16          27           55          1
19       102   MT-ND5             38          51           12          1

In [28]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
0         10   MT-ND1              1           1            7          1
1         11   MT-ND2              1           1            8          1
2         12    RPL41              1           1            9          1
3         14   MT-CO3              1           1           11          1
4         16   MT-CO2              1           1           13          1
5         17   MT-ND3              1           1           14          1
6         19   MT-ND4              1           1           16          1
7         20   MT-CYB              1           1           17          1
8         21   MT-CO1              1           1           18          1
9         25  MT-ATP6              1           1           22          1
10        40  MT-RNR1              1           1           37          1
11        74     RPS9             25          42            6          1
12        75    RPL28             22          31           21          1
13        77    RPLP1             23          30           23          1
14        79    RPS28             26          37           15          1
15        79    RPS27             19          29           30          1
17        82      FAU             20          60            1          1
16        82  MT-RNR2              1           1           79          1
18        99    RPL39             16          27           55          1
19       102   MT-ND5             38          51           12          1

   Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
0            MSI         MSI         MSI       MSI  MSI_high
1            MSI         MSI         MSI       MSI  MSI_high
2            MSI         MSI         MSI       MSI  MSI_high
3            MSI         MSI         MSI       MSI  MSI_high
4            MSI         MSI         MSI       MSI  MSI_high
5            MSI         MSI         MSI       MSI  MSI_high
6            MSI         MSI         MSI       MSI  MSI_high
7            MSI         MSI         MSI       MSI  MSI_high
8            MSI         MSI         MSI       MSI  MSI_high
9            MSI         MSI         MSI       MSI  MSI_high
10           MSI         MSI         MSI       MSI  MSI_high
11           MSI         MSI         MSI       MSI  MSI_high
12           MSI         MSI         MSI       MSI  MSI_high
13           MSI         MSI         MSI       MSI  MSI_high
14           MSI         MSI         MSI       MSI  MSI_high
15           MSI         MSI         MSI       MSI  MSI_high
17           MSI         MSI         MSI       MSI  MSI_high
16           MSI         MSI         MSI       MSI  MSI_high
18           MSI         MSI         MSI       MSI  MSI_high
19           MSI         MSI         MSI       MSI  MSI_high

In [29]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,10,MT-ND1,1,1,7,1,MSI,MSI,MSI,MSI,MSI_high
1,11,MT-ND2,1,1,8,1,MSI,MSI,MSI,MSI,MSI_high
2,12,RPL41,1,1,9,1,MSI,MSI,MSI,MSI,MSI_high
3,14,MT-CO3,1,1,11,1,MSI,MSI,MSI,MSI,MSI_high
4,16,MT-CO2,1,1,13,1,MSI,MSI,MSI,MSI,MSI_high
5,17,MT-ND3,1,1,14,1,MSI,MSI,MSI,MSI,MSI_high
6,19,MT-ND4,1,1,16,1,MSI,MSI,MSI,MSI,MSI_high
7,20,MT-CYB,1,1,17,1,MSI,MSI,MSI,MSI,MSI_high
8,21,MT-CO1,1,1,18,1,MSI,MSI,MSI,MSI,MSI_high
9,25,MT-ATP6,1,1,22,1,MSI,MSI,MSI,MSI,MSI_high
10,40,MT-RNR1,1,1,37,1,MSI,MSI,MSI,MSI,MSI_high
11,74,RPS9,25,42,6,1,MSI,MSI,MSI,MSI,MSI_high
12,75,RPL28,22,31,21,1,MSI,MSI,MSI,MSI,MSI_high
13,77,RPLP1,23,30,23,1,MSI,MSI,MSI,MSI,MSI_high
14,79,RPS28,26,37,15,1,MSI,MSI,MSI,MSI,MSI_high
15,79,RPS27,19,29,30,1,MSI,MSI,MSI,MSI,MSI_high
16,82,MT-RNR2,1,1,79,1,MSI,MSI,MSI,MSI,MSI_high
17,82,FAU,20,60,1,1,MSI,MSI,MSI,MSI,MSI_high
18,99,RPL39,16,27,55,1,MSI,MSI,MSI,MSI,MSI_high
19,102,MT-ND5,38,51,12,1,MSI,MSI,MSI,MSI,MSI_high

In [30]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,38858,1192,12335,10137,15194,MSI,MSI,MSI,MSI,MSI_high
1,LYVE1,37442,1192,11268,13035,11947,MSS,MSS,MSI,MSS,MSS_high
2,CLEC5A,42206,1192,12929,12891,15194,MSI,MSS,MSS,MSS,MSS_high
3,CX3CR1,2656,1192,221,546,697,MSI,MSI,MSI,MSI,MSI_high
4,FN1,38734,1192,11741,10607,15194,MSS,MSS,MSS,MSS,MSS_high
5,IL11,34422,1192,6987,14296,11947,MSI,MSI,NaN,MSS,MSS_high
6,NRAP,43611,1192,12929,14296,15194,MSS,MSS,NaN,MSS,MSS_high
7,SDC1,34937,1192,10334,9553,13858,MSS,MSS,MSS,MSS,MSS_high
8,SCG5,43611,1192,12929,14296,15194,MSS,MSS,NaN,MSS,MSS_high

In [31]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,38858,1192,12335,10137,15194,MSI,MSI,MSI,MSI,MSI_high,9714
1,LYVE1,37442,1192,11268,13035,11947,MSS,MSS,MSI,MSS,MSS_high,9360
2,CLEC5A,42206,1192,12929,12891,15194,MSI,MSS,MSS,MSS,MSS_high,10552
3,CX3CR1,2656,1192,221,546,697,MSI,MSI,MSI,MSI,MSI_high,664
4,FN1,38734,1192,11741,10607,15194,MSS,MSS,MSS,MSS,MSS_high,9684
5,IL11,34422,1192,6987,14296,11947,MSI,MSI,NaN,MSS,MSS_high,8606
6,NRAP,43611,1192,12929,14296,15194,MSS,MSS,NaN,MSS,MSS_high,10903
7,SDC1,34937,1192,10334,9553,13858,MSS,MSS,MSS,MSS,MSS_high,8734
8,SCG5,43611,1192,12929,14296,15194,MSS,MSS,NaN,MSS,MSS_high,10903