In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw$ ls
Wilcoxon_DEG_Bcell_raw.csv       Wilcoxon_DEG_Mast_raw.csv     Wilcoxon_DEG_Neutrophil_raw.csv  Wilcoxon_DEG_random10_raw.csv
Wilcoxon_DEG_Epithelial_raw.csv  Wilcoxon_DEG_Myeloid_raw.csv  Wilcoxon_DEG_Plasma_raw.csv      Wilcoxon_DEG_Stromal_raw.csv

yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_Limmatrend_raw$ ls
LIMMATREND_DEG_B_cell_raw.csv      LIMMATREND_DEG_mast_raw.csv     LIMMATREND_DEG_neutrophil_raw.csv  LIMMATREND_DEG_random10_raw.csv
LIMMATREND_DEG_epithelial_raw.csv  LIMMATREND_DEG_myeloid_raw.csv  LIMMATREND_DEG_plasma_raw.csv      LIMMATREND_DEG_stromal_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw$ ls
RISCQP_DEG_b_cell_raw.csv      RISCQP_DEG_mast_raw.csv     RISCQP_DEG_neutrophil_raw.csv  RISCQP_DEG_stromal_raw.csv
RISCQP_DEG_Epithelial_raw.csv  RISCQP_DEG_myeloid_raw.csv  RISCQP_DEG_random10_raw.csv

In [ ]:
yeonu@gpusystem:/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw$ ls
MAST_raw_B_cell.csv      MAST_raw_mast_cell.csv     MAST_raw_neutrophil.csv  MAST_raw_random10.csv
MAST_raw_Epithelial.csv  MAST_raw_myeloid_cell.csv  MAST_raw_plasma.csv      MAST_raw_stromal.csv

In [1]:
import pandas as pd
import numpy as np

### 데이터 정제

In [2]:
# 1. DEG_Wilcoxon 전처리 
# Wilcoxon_DEG : Wilcoxon_DEG_~.csv

df_wilcoxon = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_Wilcoxon/DEG_Wilcoxon_raw/Wilcoxon_DEG_Stromal_raw.csv')
print(df_wilcoxon.shape)
print(df_wilcoxon.head())
df_wilcoxon = df_wilcoxon[["names", "logfoldchanges", "pvals", "pvals_adj"]]
df_wilcoxon.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "Wilcoxon_adj_pval"}, inplace=True)
print(df_wilcoxon.head())

(28476, 5)
     names      scores  logfoldchanges  pvals  pvals_adj
0  MT-ND4L  144.471710        3.700602    0.0        0.0
1    RPL28  128.666840        1.998709    0.0        0.0
2  MT-ATP8  127.714560        4.058124    0.0        0.0
3   MT-CO1  119.802376        2.073982    0.0        0.0
4    RPL10  117.334404        1.503643    0.0        0.0
      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        3.700602   0.0                0.0
1    RPL28        1.998709   0.0                0.0
2  MT-ATP8        4.058124   0.0                0.0
3   MT-CO1        2.073982   0.0                0.0
4    RPL10        1.503643   0.0                0.0

In [3]:
df_wilcoxon.head(2)

      gene  logfoldchanges  pval  Wilcoxon_adj_pval
0  MT-ND4L        3.700602   0.0                0.0
1    RPL28        1.998709   0.0                0.0

In [4]:
# 2. DEG_limatrend 전처리 
# limatrend_DEG : limmatrend_DEG_~.csv

df_limmatrend = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_limmatrend/DEG_limmatrend_raw/LIMMATREND_DEG_stromal_raw.csv')
print(df_limmatrend.shape)
print(df_limmatrend.head(2))
df_limmatrend = df_limmatrend[["names", "logfoldchanges", "pvals", "pvals_adj"]]
print((df_limmatrend.head()))
df_limmatrend.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "limmatrend_adj_pval"}, inplace=True)
print(df_limmatrend.head())

(28476, 4)
     names  pvals  pvals_adj  logfoldchanges
0  MT-ND4L    0.0        0.0       -1.572465
1  MT-ATP8    0.0        0.0       -1.221551
     names  logfoldchanges  pvals  pvals_adj
0  MT-ND4L       -1.572465    0.0        0.0
1  MT-ATP8       -1.221551    0.0        0.0
2  MT-RNR2        2.366534    0.0        0.0
3    RPL28       -1.206565    0.0        0.0
4   MT-CO1       -1.771133    0.0        0.0
      gene  logfoldchanges  pval  limmatrend_adj_pval
0  MT-ND4L       -1.572465   0.0                  0.0
1  MT-ATP8       -1.221551   0.0                  0.0
2  MT-RNR2        2.366534   0.0                  0.0
3    RPL28       -1.206565   0.0                  0.0
4   MT-CO1       -1.771133   0.0                  0.0

In [5]:
df_limmatrend.head(2)

      gene  logfoldchanges  pval  limmatrend_adj_pval
0  MT-ND4L       -1.572465   0.0                  0.0
1  MT-ATP8       -1.221551   0.0                  0.0

In [6]:
# 3. RISCQP_DEG 전처리
# DEG_RISCQP : RISCQP_DEG_-.csv

df_RISCQP = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_RISCQP/DEG_RISCQP_raw/RISCQP_DEG_stromal_raw.csv')
print(df_RISCQP.shape)
print(df_RISCQP.head())
df_RISCQP = df_RISCQP[["Symbol", "log2FC", "Pvalue", "Padj"]]
df_RISCQP.rename(columns={"Symbol": "gene","Pvalue": "pval","Padj": "RISCQP_adj_pval"}, inplace=True)
print(df_RISCQP.head())

(24011, 10)
  Unnamed: 0   Symbol  Percent  Pct.Ctl  Pct.Sam  avelog.Ctl  avelog.Sam  \
0       GNB1     GNB1    0.502    0.660    0.266    1.552341    3.960607
1      RPL22    RPL22    0.746    0.641    0.904    6.234718    4.110763
2       RERE     RERE    0.389    0.474    0.262    1.521336    2.745961
3      KIF1B    KIF1B    0.267    0.351    0.140    0.786339    1.980983
4    PLEKHM2  PLEKHM2    0.192    0.264    0.083    0.465309    1.441342

     log2FC  Pvalue  Padj
0  3.789920     0.0   0.0
1 -3.085237     0.0   0.0
2  2.026588     0.0   0.0
3  2.386399     0.0   0.0
4  2.445005     0.0   0.0
      gene    log2FC  pval  RISCQP_adj_pval
0     GNB1  3.789920   0.0              0.0
1    RPL22 -3.085237   0.0              0.0
2     RERE  2.026588   0.0              0.0
3    KIF1B  2.386399   0.0              0.0
4  PLEKHM2  2.445005   0.0              0.0

In [7]:
df_RISCQP.head(2)

    gene    log2FC  pval  RISCQP_adj_pval
0   GNB1  3.789920   0.0              0.0
1  RPL22 -3.085237   0.0              0.0

In [8]:
# 5. DEG_MAST 전처리 
# MAST_DEG : MAST_DEG_~.csv

df_MAST = pd.read_csv('/nas/arpa_h_repository/public_data/CRC_Atlas_1/CRC-Atlas-Split/crc-atlas/Deg_data/DEG_MAST/DEG_MAST_raw/MAST_raw_stromal.csv')
print(df_MAST.shape)
print(df_MAST.head(2))
# df_MAST = df_MAST[["names", "logfoldchanges", "pvals", "pvals_adj"]]
# print((df_MAST.head()))
df_MAST.rename(columns={"names": "gene","pvals": "pval","pvals_adj": "MAST_adj_pval"}, inplace=True)
print(df_MAST.head())

(28476, 4)
   names  logfoldchanges  pvals  pvals_adj
0   A1BG       -0.075359    0.0        0.0
1  ABCA8       -0.213719    0.0        0.0
          gene  logfoldchanges  pval  MAST_adj_pval
0         A1BG       -0.075359   0.0            0.0
1        ABCA8       -0.213719   0.0            0.0
2        ABCB1        0.069995   0.0            0.0
3  ABCF2-H2BK1       -0.040924   0.0            0.0
4         ABL1        0.090814   0.0            0.0

In [9]:
df_MAST.head(2)

    gene  logfoldchanges  pval  MAST_adj_pval
0   A1BG       -0.075359   0.0            0.0
1  ABCA8       -0.213719   0.0            0.0

## <font color="red">**MSS/MSI 데이터프레임**

In [10]:
import pandas as pd
from functools import reduce

# 1) 미리 각 df에서 gene + adj_pval 컬럼만 추출
dfs = [
    df_wilcoxon[["gene", "Wilcoxon_adj_pval"]],
    df_limmatrend[["gene", "limmatrend_adj_pval"]],
    df_RISCQP[["gene", "RISCQP_adj_pval"]],
    df_MAST[["gene", "MAST_adj_pval"]],
    # df_monocle_filtered[["gene", "monocle_adj_pval"]],
]

# 2) Reduce를 이용해 순차적으로 outer merge
df_mmm = reduce(
    lambda left, right: pd.merge(left, right, on="gene", how="outer"),
    dfs
)

# 결과 확인
print(df_mmm.shape)
print(df_mmm.head())

(28476, 5)
          gene  Wilcoxon_adj_pval  limmatrend_adj_pval  RISCQP_adj_pval  \
0    5S_rRNA-2                1.0                  1.0              NaN
1    5S_rRNA-5                1.0                  1.0              NaN
2    5_8S_rRNA                1.0                  1.0              NaN
3  5_8S_rRNA-1                1.0                  1.0              NaN
4  5_8S_rRNA-2                1.0                  1.0              NaN

   MAST_adj_pval
0            1.0
1            1.0
2            1.0
3            1.0
4            1.0

In [11]:
df_mmm.head(2)

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval
0,5S_rRNA-2,1.0,1.0,NaN,1.0
1,5S_rRNA-5,1.0,1.0,NaN,1.0

In [12]:
# 1) 각 컬럼별 rank 계산 (값이 작을수록 1위, NaN은 가장 마지막)
df_mmm['rank_wilcoxon'] = df_mmm['Wilcoxon_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_limma'] = df_mmm['limmatrend_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_RISCQP'] = df_mmm['RISCQP_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)

df_mmm['rank_MAST'] = df_mmm['MAST_adj_pval'] \
    .rank(method='min', ascending=True, na_option='bottom').astype(int)


# 2) 5개 rank의 합 계산
df_mmm['rank_sum'] = df_mmm[
    ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']
].sum(axis=1)

# 3) rank_sum 기준으로 정렬
df_mmm = df_mmm.sort_values('rank_sum').reset_index(drop=True)

# 결과 확인 (선택사항)
df_mmm

,gene,Wilcoxon_adj_pval,limmatrend_adj_pval,RISCQP_adj_pval,MAST_adj_pval,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,rank_sum
0,CXCL12,0.0,0.0,0.0,0.0,1,1,1,1,4
1,RPS23,0.0,0.0,0.0,0.0,1,1,1,1,4
2,PTPRG,0.0,0.0,0.0,0.0,1,1,1,1,4
3,PTPRM,0.0,0.0,0.0,0.0,1,1,1,1,4
4,TBC1D1,0.0,0.0,0.0,0.0,1,1,1,1,4
...,...,...,...,...,...,...,...,...,...,...
28471,5S_rRNA-5,1.0,1.0,NaN,1.0,13672,25716,24012,25866,89266
28472,hsa-mir-8069-1,1.0,1.0,NaN,1.0,13672,25716,24012,25866,89266
28473,5S_rRNA-2,1.0,1.0,NaN,1.0,13672,25716,24012,25866,89266
28474,5_8S_rRNA-8,1.0,1.0,NaN,1.0,13672,25716,24012,25866,89266
28475,5_8S_rRNA-2,1.0,1.0,NaN,1.0,13672,25716,24012,25866,89266

In [13]:
df_mmm_re = df_mmm[['rank_sum', 'gene', 'rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']]
df_mmm_re.head(20)

    rank_sum     gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST
0          4   CXCL12              1           1            1          1
1          4    RPS23              1           1            1          1
2          4    PTPRG              1           1            1          1
3          4    PTPRM              1           1            1          1
4          4   TBC1D1              1           1            1          1
5          4    ITGA1              1           1            1          1
6          4    RPL39              1           1            1          1
7          4  TMEM35B              1           1            1          1
8          4     JUND              1           1            1          1
9          4     PPIB              1           1            1          1
10         4    CXCL1              1           1            1          1
11         4   HNRNPD              1           1            1          1
12         4    RGS10              1           1            1          1
13         4     APOE              1           1            1          1
14         4   APOLD1              1           1            1          1
15         4  C1orf54              1           1            1          1
16         4     EMP3              1           1            1          1
17         4     RPL5              1           1            1          1
18         4     RPL6              1           1            1          1
19         4    RPL7A              1           1            1          1

In [14]:
import pandas as pd
from functools import reduce

# 1️⃣ 각 메서드별 “gene + sign” DataFrame 생성
sign_dfs = []

# Wilcoxon: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_wilcoxon[['gene','logfoldchanges']]
    .assign(Wilcoxon_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
    [['gene','Wilcoxon_sign']]
)

# limmatrend: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_limmatrend[['gene','logfoldchanges']]
    .assign(limmat_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','limmat_sign']]
)

# RISCQP: log2FC <0 → MSI, >0 → MSS
sign_dfs.append(
    df_RISCQP[['gene','log2FC']]
    .assign(RISCQP_sign=lambda d: d['log2FC'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','RISCQP_sign']]
)

# 


# # MAST: logfoldchanges >0 → MSI, <0 → MSS
# sign_dfs.append(
#     df_MAST[['gene','logfoldchanges']]
#     .assign(MAST_sign=lambda d: d['logfoldchanges'].gt(0).map({True:'MSI', False:'MSS'}))
#     [['gene','MAST_sign']]
# )

# MAST: logfoldchanges >0 → MSI, <0 → MSS
sign_dfs.append(
    df_MAST[['gene','logfoldchanges']]
    .assign(MAST_sign=lambda d: d['logfoldchanges'].lt(0).map({True:'MSI', False:'MSS'}))
    [['gene','MAST_sign']]
)

# 2️⃣ 모든 sign DataFrame outer merge
sign_df = reduce(lambda a,b: pd.merge(a,b,on='gene',how='outer'), sign_dfs)

# 3️⃣ rank 합계 df와 결합
df_final = df_mmm_re.merge(sign_df, on='gene', how='left')

# 4️⃣ consensus: MSI_sign이 3개 이상 → MSI_high, else MSS_high
sign_cols = [col for col in df_final.columns if col.endswith('_sign')]
df_final['consensus'] = df_final[sign_cols].apply(
    lambda row: 'MSI_high' if (row=='MSI').sum() >= 3 else 'MSS_high',
    axis=1
)

# 5️⃣ 결과 확인 (상위 20개)
print(df_final.sort_values('rank_sum').head(20))

     rank_sum        gene  rank_wilcoxon  rank_limma  rank_RISCQP  rank_MAST  \
78          4       RPL37              1           1            1          1
88          4      IFITM1              1           1            1          1
87          4        GNB1              1           1            1          1
86          4        PHC2              1           1            1          1
85          4       RPS4X              1           1            1          1
84          4  PALM2AKAP2              1           1            1          1
83          4      NFE2L1              1           1            1          1
82          4         QKI              1           1            1          1
81          4       RPL32              1           1            1          1
80          4       RPL30              1           1            1          1
79          4       RPL29              1           1            1          1
89          4        AKT3              1           1            1          1
121         4      RASAL2              1           1            1          1
120         4        RPS5              1           1            1          1
119         4       PFDN5              1           1            1          1
118         4         LPP              1           1            1          1
117         4       LAMC1              1           1            1          1
116         4      ABLIM1              1           1            1          1
115         4       CRIP2              1           1            1          1
114         4     SLC25A6              1           1            1          1

    Wilcoxon_sign limmat_sign RISCQP_sign MAST_sign consensus
78            MSI         MSI         MSI       MSI  MSI_high
88            MSI         MSI         MSI       MSI  MSI_high
87            MSS         MSS         MSS       MSS  MSS_high
86            MSS         MSS         MSS       MSS  MSS_high
85            MSI         MSI         MSI       MSI  MSI_high
84            MSS         MSS         MSS       MSS  MSS_high
83            MSS         MSS         MSS       MSS  MSS_high
82            MSS         MSS         MSS       MSS  MSS_high
81            MSI         MSI         MSI       MSI  MSI_high
80            MSI         MSI         MSI       MSI  MSI_high
79            MSI         MSI         MSI       MSI  MSI_high
89            MSS         MSS         MSS       MSS  MSS_high
121           MSS         MSS         MSS       MSS  MSS_high
120           MSI         MSI         MSI       MSI  MSI_high
119           MSI         MSI         MSI       MSI  MSI_high
118           MSS         MSS         MSS       MSS  MSS_high
117           MSS         MSS         MSS       MSS  MSS_high
116           MSS         MSS         MSS       MSS  MSS_high
115           MSS         MSS         MSS       MSS  MSS_high
114           MSI         MSI         MSI       MSI  MSI_high

In [15]:
df_final.head(20)

,rank_sum,gene,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,4,CXCL12,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
1,4,RPS23,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
2,4,PTPRG,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
3,4,PTPRM,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
4,4,TBC1D1,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
5,4,ITGA1,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
6,4,RPL39,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
7,4,TMEM35B,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
8,4,JUND,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
9,4,PPIB,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
10,4,CXCL1,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
11,4,HNRNPD,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
12,4,RGS10,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
13,4,APOE,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
14,4,APOLD1,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
15,4,C1orf54,1,1,1,1,MSS,MSS,MSS,MSS,MSS_high
16,4,EMP3,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
17,4,RPL5,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
18,4,RPL6,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high
19,4,RPL7A,1,1,1,1,MSI,MSI,MSI,MSI,MSI_high

In [16]:
# 원하는 순서의 리스트
genes_of_interest = ["VSIG4", "LYVE1", "CLEC5A", "CX3CR1", "FN1", "IL11", "NRAP", "SDC1", "SCG5"]
df_final_filtered = df_final[df_final["gene"].isin(genes_of_interest)]
df_final_filtered

# 2) gene을 인덱스로 설정한 뒤 순서대로 선택
df_final_filtered = (
    df_final_filtered
    .set_index('gene')
    .loc[genes_of_interest]         # order 순서대로 행 재정렬
    .reset_index()                  # 다시 gene을 컬럼으로
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus
0,VSIG4,66171,13672,18508,15922,18069,MSS,MSS,MSS,MSS,MSS_high
1,LYVE1,36289,9042,8043,7871,11333,MSS,MSS,MSS,MSS,MSS_high
2,CLEC5A,74852,13672,19570,18663,22947,MSS,MSS,MSS,MSS,MSS_high
3,CX3CR1,67277,13672,17731,16187,19687,MSS,MSS,MSS,MSS,MSS_high
4,FN1,30059,7405,4532,12641,5481,MSS,MSS,MSS,MSS,MSS_high
5,IL11,10943,5056,1722,1951,2214,MSI,MSI,MSI,MSI,MSI_high
6,NRAP,70065,13672,15906,22951,17536,MSS,MSS,MSI,MSS,MSS_high
7,SDC1,84337,13672,24198,20872,25595,MSI,MSI,MSI,MSI,MSI_high
8,SCG5,34538,8532,8713,7261,10032,MSS,MSS,MSS,MSS,MSS_high

In [17]:
# 사용할 컬럼 리스트
rank_cols = ['rank_wilcoxon', 'rank_limma', 'rank_RISCQP', 'rank_MAST']

# # rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
# df_final_filtered['rank_mean'] = df_final_filtered[rank_cols].mean(axis=1)

# rank_mean 컬럼 생성: 행(row) 단위로 평균 계산
df_final_filtered['rank_mean'] = (
    df_final_filtered[rank_cols]
    .mean(axis=1)          # 평균 계산
    .round()               # 소수 첫째 자리 반올림
    .astype(int)           # 정수형 변환
)

df_final_filtered

,gene,rank_sum,rank_wilcoxon,rank_limma,rank_RISCQP,rank_MAST,Wilcoxon_sign,limmat_sign,RISCQP_sign,MAST_sign,consensus,rank_mean
0,VSIG4,66171,13672,18508,15922,18069,MSS,MSS,MSS,MSS,MSS_high,16543
1,LYVE1,36289,9042,8043,7871,11333,MSS,MSS,MSS,MSS,MSS_high,9072
2,CLEC5A,74852,13672,19570,18663,22947,MSS,MSS,MSS,MSS,MSS_high,18713
3,CX3CR1,67277,13672,17731,16187,19687,MSS,MSS,MSS,MSS,MSS_high,16819
4,FN1,30059,7405,4532,12641,5481,MSS,MSS,MSS,MSS,MSS_high,7515
5,IL11,10943,5056,1722,1951,2214,MSI,MSI,MSI,MSI,MSI_high,2736
6,NRAP,70065,13672,15906,22951,17536,MSS,MSS,MSI,MSS,MSS_high,17516
7,SDC1,84337,13672,24198,20872,25595,MSI,MSI,MSI,MSI,MSI_high,21084
8,SCG5,34538,8532,8713,7261,10032,MSS,MSS,MSS,MSS,MSS_high,8634